[WIP] Feature/3454 pkg upgrade
fecgov/fec-cms pull request #3536
Opened 2020-02-10 17:44 UTC by pkfec

## Summary (required)
Pillow is child pkg of Wagtail and the latest version of Wagtail v2.8 comes with the pillow v6.2.2. While updating wagtail, i noticed that the wagtail v2.8 is compatible with Django v3.0. So i went ahead and updated Django  to latest v3.0.3.

Update  Wagtail to v2.8 and Django to v3.0.3 

- Resolves 
#3454
#3529 
#3482 
#3478 
#3105 
#3396 
#3422 

_Include a summary of proposed changes._

1.  remove  the pkg called `six`  thats not required. SET_NULL on delete flag
2.  django3.0.3  - django.core.urlresolvers is deprecated. Replace it with django.urls
3.  As of Django 1.9, the old way of including the admin urls is deprecated. pass admin.site.urls directly to url(), without the call to include().
4.  {% load staticfiles %} is deprecated in Django 2.1, and removed in Django 3.0. Replaced {% load staticfiles %} tag with {% load static %} in template files.
5.  Django 3.0.3: ForeignKey field requires on_delete argument
6.  Django 2.0 has dropped support for old-style middleware classes in MIDDLEWARE_CLASSES. Renamed it as MIDDLEWARE.
7. Upgrade Wagtail v2.8, Django v3.0.3, Django-jinja v2.5.0

## Impacted areas of the application

- Prod wagtail
- fec-cms app

## How to test
Include any information that may be helpful to the reviewer(s).
  This might include:
  - links to sample pages to test
  - Any local environmental setup that is different than the usual (env vars, API version to point to)
____

2020-02-10 18:19 UTC, johnnyporkchops commented
We should push this to feature space so we can have content team do a through test of Wagtail functionality.

2020-02-10 18:33 UTC, johnnyporkchops commented
Although we do not have to, itI may actually be helpful to squash migrations before `makemigrations` for this PR because it would remove migrations that cancel each other out . For example"
`0006_auto_20150819_0546.py` creates OptionsPage model....
`0013_auto_20160427_2133.py` removes OptionsPage model

2020-02-10 18:36 UTC, pkfec commented
> We should push this to feature space so we can have content team do a through test of Wagtail functionality.

@johnnyporkchops I second that. I would want you and @patphongs got over the changes in the PR first and approve  before i push this branch to `feature` space

2020-02-12 16:40 UTC, patphongs commented on requirements.txt
> +wagtail==2.8
@pkfec I recommend upgrading to the long term support (LTS) versions of Django and Wagtail. This will ensure greater support especially for patches and fixes than a version that is not supported. [Django 2.2](https://www.djangoproject.com/download/#supported-versions) is LTS until 4/2022 and [Wagtail 2.7](https://github.com/wagtail/wagtail/wiki/Release-schedule) is LTS until 2/2021.

2020-02-12 16:41 UTC, patphongs requested changes
Please see my recommendation

2020-02-19 14:38 UTC, pkfec commented on requirements.txt
> +wagtail==2.8
@patphongs thanks for feedback. I am going to downgrade the wagtail and django pkg to the LTS version. I will submit a new PR with the LTS version of those packages.

2020-02-20 22:16 UTC, pkfec commented
LTS versions of Wagtail v2.7 and Django v2.2.10 upgrades are being tracked in this PR #3536 

Closing this PR.

2020-02-20 22:16 UTC, closed without merging