Display committee section only when cmte_dsgn is of type P, A or J.
fecgov/fec-cms pull request #4337
Opened 2021-01-22 03:32 UTC by pkfec

## Summary (required)

Display committee section only when cmte_dsgn is of type P, A or J.

- Resolves #[_Issue number_]
_Include a summary of proposed changes._

## Impacted areas of the application

List general components of the application that this PR will affect:

-  

## Screenshots

- _Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface or front-end change, include both Before and After screenshots._

## Related PRs

List related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

Include any information that may be helpful to the reviewer(s).
_This might include:_

- links to sample pages to test
- Any local environmental setup that is unusual (env vars, API version to point to, etc)

____

2021-01-22 16:45 UTC, johnnyporkchops approved these changes
Tested locally, works  good!

2021-01-25 16:51 UTC, patphongs commented on fec/data/templates/partials/candidate/about-candidate.jinja
> +        <h3 class="heading--section">Committees</h3>
We'll actually want to leave this section heading above this if condition since that's the heading for the entire section

2021-01-25 16:52 UTC, patphongs commented on fec/data/templates/partials/candidate/about-candidate.jinja
>      <div class="entity__figure entity__figure--narrow row" id="committees">
Above this div for the committees section, we'll want to put in this condition: `{% if committee_groups['P'] or committee_groups['A'] or committee_groups['J'] %}`. At the end of this div, you'll need to terminate the if condition there.

2021-01-25 16:53 UTC, patphongs reviewed
Thanks @pkfec, just a few changes needed, let me know if you have any questions

2021-01-25 18:02 UTC, JonellaCulmer commented on fec/data/templates/partials/candidate/about-candidate.jinja
>      <div class="entity__figure entity__figure--narrow row" id="committees">
@patphongs Thank you for that comment. That was going to be my request as well - eliminating the entire section so the empty white box does not appear.

2021-01-25 18:20 UTC, pkfec commented on fec/data/templates/partials/candidate/about-candidate.jinja
>      <div class="entity__figure entity__figure--narrow row" id="committees">
> Above this div for the committees section, we'll want to put in this condition: `{% if committee_groups['P'] or committee_groups['A'] or committee_groups['J'] %}`. At the end of this div, you'll need to terminate the if condition there. Doing this will hide the entire committees section, so that we don't have an additional empty white box showing that section

@patphongs Thanks for reviewing this PR. I made above changes. Please review now.

2021-01-25 18:47 UTC, fec-jli commented
Do we want to show this white space?
<img width="815" alt="Screen Shot 2021-01-25 at 1 43 28 PM" src="https://user-images.githubusercontent.com/24395751/105751278-ca6b9e80-5f13-11eb-82f5-ca6b6b85823f.png">

2021-01-25 21:38 UTC, pkfec commented
> Do we want to show this white space?
> <img alt="Screen Shot 2021-01-25 at 1 43 28 PM" width="815" src="https://user-images.githubusercontent.com/24395751/105751278-ca6b9e80-5f13-11eb-82f5-ca6b6b85823f.png">


@fec-jli - I fixed the white space after @patphongs had a comment and pushed a changes 3 hours ago.
 Here is the latest screenshot. 
<img width="1194" alt="Screen Shot 2021-01-25 at 4 35 27 PM" src="https://user-images.githubusercontent.com/11650355/105769160-66ed6b00-5f2b-11eb-88a1-0741bea07fd1.png">

2021-01-25 21:50 UTC, fec-jli approved these changes
good job, Thanks

2021-01-25 21:53 UTC, patphongs requested changes
@pkfec Thanks for making those changes. I have one last change request. On [line 102](https://github.com/fecgov/fec-cms/blob/5dd8a10176a82181217529897153924fb5a57e19/fec/data/templates/partials/candidate/about-candidate.jinja#L102) there's a closing `{% endif %}` that should be moved to the closing div of the `id=committees` section (second to last div on the about-candidates.jinja.

2021-01-25 22:45 UTC, pkfec commented
> @pkfec Thanks for making those changes. I have one last change request. On [line 102](https://github.com/fecgov/fec-cms/blob/5dd8a10176a82181217529897153924fb5a57e19/fec/data/templates/partials/candidate/about-candidate.jinja#L102) there's a closing `{% endif %}` that should be moved to after the closing div of the `id=committees` section (second to last div on the about-candidates.jinja).

@patphongs Sorry, i missed your comment. I fixed it now, please check.

2021-01-26 13:47 UTC, JonellaCulmer approved these changes
Thanks for making that fix to remove the box when there are no committees. That was my only comment.

2021-01-26 15:04 UTC, patphongs approved these changes
Looks good now, thanks @pkfec!

2021-01-26 15:05 UTC, merged