Feature/4351 debts section
fecgov/fec-cms pull request #4353
Opened 2021-01-28 16:48 UTC by rfultz

## Summary

- Resolves #4351  
Adding the debts section!

## Reviewers
- Paul for purpose and expertise (general and detailed)
- UX for, uh, UX concerns
- Back-end to verify proper integration
- Front-end for functionality

## Impacted areas of the application

- Updated `/data/browse-data/?tab=loans-debts` to activate the Debts section
- Created `/data/debts/`
- Changed range filters' naming logic, which should only add flexibility

## Screenshots

Current
![image](https://user-images.githubusercontent.com/26720877/106168770-ab138200-615c-11eb-8c88-7194d49c5b85.png)

New
![image](https://user-images.githubusercontent.com/26720877/106168871-c3839c80-615c-11eb-92b0-44311d8fac2f.png)
![image](https://user-images.githubusercontent.com/26720877/106168923-cda59b00-615c-11eb-9a6e-b9acc390fe0f.png)

Details panel
![image](https://user-images.githubusercontent.com/26720877/106168964-d9915d00-615c-11eb-8ed3-b86cb17451d6.png)

## Related PRs

None

## How to test

- Pull branch
- `npm i`, `npm run build`
- `./manage.py runserver`
- Go to the [loans/debts section](http://127.0.0.1:8000/data/browse-data/?tab=loans-debts)
- Play with the debts [/data/debts/](http://127.0.0.1:8000/data/debts/)
- **NOTE**: the dollar filters don't currently work!
They'll come online with https://github.com/fecgov/openFEC/issues/4755
- Because of the change to the range filters' names:
  - Check other datatables' range filters where there is one 'amount' range (not a date range)
  - Check where there are multiple 'amount' ranges on the same table. Looking at the code, these have two or more range.amount filters:
    - debts (obviously)
    - loans
    - reports
  - Range filters should function like normal: filter data properly, add & remove chiclets properly

____

2021-01-29 17:09 UTC, lbeaufort commented
@rfultz looks great! Thanks so much for your work on this. Two comments:

### Creditor/debtor search
The `CREDITOR/DEBTOR NAME OR ID` field (or `creditor_debtor_name` in the API) is currently only a committee ID lookup/typeahead in the front end. However, the data only has `creditor_debtor_name` (only one has a committee ID in it) so using a committe ID lookup won't return results. I think instead it should be a freetext field that searches `creditor_debtor_name`. Maybe just `CREDITOR/DEBTOR NAME` in the front end.

In the example below, we can't search for the word "hotel", we have to choose a committee:
<img width="1043" alt="Screen Shot 2021-01-29 at 11 59 17 AM" src="https://user-images.githubusercontent.com/31420082/106305432-af0dd580-622a-11eb-990d-6dd0cff435c4.png">

### Breadcrumb
I think the `debt` breadcrumb should be capitalized:
<img width="473" alt="Screen Shot 2021-01-29 at 11 44 40 AM" src="https://user-images.githubusercontent.com/31420082/106305531-cd73d100-622a-11eb-95af-bf97a712e314.png">

2021-01-29 17:30 UTC, rfultz commented
Good catches, @lbeaufort ! Changes are on their way up
(I only went with 'debts' because that's how 'loans' was. I've capped 'em both

2021-01-29 17:37 UTC, lbeaufort approved these changes
Looks great! Thanks for adding this helpful feature!

2021-01-29 18:55 UTC, lbeaufort commented on fec/fec/static/js/modules/filters/range-filter.js
> +  var rangeNameForTag = this.name.split('_')[1]; // (initial functionality)
Thanks for catching and documenting this quirky behavior! It might be an opportunity for a javascript test - if you agree, could you enter a follow-up ticket or add test(s)?

2021-02-02 16:48 UTC, patphongs approved these changes
Works great thanks @rfultz !

2021-02-02 16:57 UTC, JonellaCulmer commented
@dorothyyeager @kathycarothers @djgarr Would anyone be available to look at the language on the two affected pages to see if there are any edits you recommend? Particularly the browse data page.

2021-02-02 17:39 UTC, JonellaCulmer commented
@PaulClark2 @patphongs @rfultz @lbeaufort @dorothyyeager 
Question I don't have an answer to. Would like to think through the business case with content and program managers, especially if we don't have time for usability testing prior to this feature's release:
- What is the benefit of showing multiple versions of the same debt with a committee or company? I think they are per time period, but there's no time reference being made, neither on the table or in the flyout panel. Is this in the data somewhere?
<img width="1140" alt="Screen Shot 2021-02-02 at 12 08 18 PM" src="https://user-images.githubusercontent.com/31663028/106636078-8ac63780-654f-11eb-99ea-4d9d2d9de6e7.png">

This potential issues also creates the following: 
<img width="1370" alt="Screen Shot 2021-02-02 at 12 36 16 PM" src="https://user-images.githubusercontent.com/31663028/106640011-8b60cd00-6553-11eb-90d6-b5e4cf0e258d.png">


Other edits:
- Sentence case for the following table headers: Committee name, Creditor/debtor name, Beginning balance, Ending balance
- Flyout panel sentence case: Nature of debt, Balance at beginning of period, Incurred this period, Payments this period, Balance at close of period
- I think there's some wrapping that needs to happen so the columns don't bounce around as much when sorting. 
![Feb-02-2021 12-11-48](https://user-images.githubusercontent.com/31663028/106636463-f5777300-654f-11eb-8643-10dd2699b404.gif)

2021-02-02 18:07 UTC, djgarr commented
> @dorothyyeager @kathycarothers @djgarr Would anyone be available to look at the language on the two affected pages to see if there are any edits you recommend? Particularly the browse data page.

I can help. The only change I see on the Browse data page would be to remove the last comma in the sentence under Debts.

2021-02-02 18:07 UTC, dorothyyeager commented
Tagging @bmathesonFEC on the content side who is more familiar with this but to me that image above showed the gradual reduction of the debt that was being reported.

2021-02-02 19:02 UTC, PaulClark2 commented
@JonellaCulmer technically they aren't the same. We are show as-amend debt transactions reported on various reports.  See below with added report-level information.  

This is not the place, but the limited space in the data tables has always been a short-coming in my mind. The details panel requires an extra step to get needed information. 

I've entered a ticket to add report-level information to the debts endpoint, https://github.com/fecgov/openFEC/issues/4758

CMTE_ID	|	RPT_YR	|	RPT_TP	|	CVG_END_DT	|	SCHED_TP_CD	|	NAME	|	DEBT_AMT_INCURRED_PER	|	DEBT_PYMT_PER	|	DEBT_OUTSTANDING_BALANCE_BOP	|	DEBT_OUTSTANDING_BALANCE_COP	|	IMAGE_NUM
----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----
C00743153	|	2020	|	Q1	|	3/31/2020	|	SD	|	ARISTOTLE	|	1950	|	0	|	0	|	1950	|	202007159244856639
C00743153	|	2020	|	Q2	|	6/30/2020	|	SD	|	ARISTOTLE	|	0	|	0	|	1950	|	1950	|	202007159244856710
C00743153	|	2020	|	12P	|	7/15/2020	|	SD	|	ARISTOTLE	|	0	|	0	|	1950	|	1950	|	202007239260753380
C00743153	|	2020	|	Q3	|	9/30/2020	|	SD	|	ARISTOTLE	|	0	|	800	|	1950	|	1150	|	202010159293945300
C00743153	|	2020	|	YE	|	12/31/2020	|	SD	|	ARISTOTLE	|	0	|	0	|	1150	|	1150	|	202101069394550463

2021-02-05 17:47 UTC, johnnyporkchops approved these changes
Works great. Thanks for finishing an issue that has been iceboxed for almost three years!
https://github.com/fecgov/openFEC-web-app/pull/1824

2021-02-08 20:40 UTC, rfultz commented on fec/fec/static/js/modules/filters/range-filter.js
> +  var rangeNameForTag = this.name.split('_')[1]; // (initial functionality)
We could add it. It’s been this long and nobody’s had the issue.

I'm open to suggestions for how it would work. Been trying to think through how we’d set up the test so it’s valuable and not just hard-coded and not using functionality built only for the test, ya know? Because why test something whose entire code exists only in tests…?

2021-02-08 21:12 UTC, lbeaufort commented on fec/fec/static/js/modules/filters/range-filter.js
> +  var rangeNameForTag = this.name.split('_')[1]; // (initial functionality)
Thanks for thinking about this @rfultz it sounds like it's ok to leave it as-is. If it becomes an issue again, we could reconsider. Thanks again!

2021-02-11 19:35 UTC, patphongs requested changes
Thanks for adding the feature flag @rfultz, just a few edits that need to happen to get it to work.

2021-02-11 19:35 UTC, patphongs commented on fec/data/urls.py
> +    url(r'^data/debts/$', views_datatables.debts),
To get this to work, you'll actually need to append it to the list of `urlpatterns` like this:

```
if settings.FEATURES.get('debts'):
    urlpatterns.append(
        url(r'^data/debts/$', views_datatables.debts),
    )
```

2021-02-11 19:35 UTC, patphongs commented on fec/data/templates/partials/browse-data/loans-debts.jinja
> +        {% else %%}
Extra `%` needs to be removed

2021-02-11 19:35 UTC, patphongs commented on fec/data/templates/partials/browse-data/loans-debts.jinja
> +        {% endif %%}
Extra `%` needs to be removed

2021-02-18 16:25 UTC, rfultz commented on fec/data/templates/partials/browse-data/loans-debts.jinja
> +        {% else %%}
Embarrassing

2021-02-18 16:25 UTC, rfultz commented on fec/data/urls.py
> +    url(r'^data/debts/$', views_datatables.debts),
On its way

2021-02-18 16:36 UTC, patphongs approved these changes
Looks good, thanks @rfultz, merging now

2021-02-18 16:37 UTC, merged