Add leadership PACs to about this candidate section of candidate profile pages
fecgov/fec-cms pull request #4358
Opened 2021-02-01 19:45 UTC by fec-jli

## Summary (required)
Add leadership PACs to the committees section in 'about this candidate' page

- Resolves #4270

## Impacted areas of the application
about this candidat section in Candidate Profile page

List general components of the application that this PR will affect:
1)Add leadership PAC to committees section
2)Add Glossary links to each of the committee subheaders

## Screenshots
<img width="462" alt="Screen Shot 2021-02-01 at 2 37 50 PM" src="https://user-images.githubusercontent.com/24395751/106509244-5ee97a00-649b-11eb-9bbc-ef281bc56559.png">

## How to test
1)checkout branch
2)run tests:
pytest
./manage.py test
./manage.py test data.tests
3)compare some examples with prod

(1)P00009092 / 2020  (only have one dsgn=P committee)
http://127.0.0.1:8000/data/candidate/P00009092/?tab=about-candidate
https://www.fec.gov/data/candidate/P00009092/?tab=about-candidate

(2)S4AR00103 /2020 (has P, A, 2J and two leadership pac committees)
http://127.0.0.1:8000/data/candidate/S4AR00103/?tab=about-candidate&cycle=2020&election_full=true
https://www.fec.gov/data/candidate/S4AR00103/?tab=about-candidate&cycle=2020&election_full=true

(3)H0MI08042 / 2014 (only has two leadership pac committees)
http://127.0.0.1:8000/data/candidate/H0MI08042/?tab=about-candidate
https://www.fec.gov/data/candidate/H0MI08042/?tab=about-candidate

(4)P00009183 / 2020  (display only one leadership pac committee)
http://127.0.0.1:8000/data/candidate/P00009183/?tab=about-candidate&election_full=true
https://www.fec.gov/data/candidate/P00009183/?tab=about-candidate

(5)H0OH08029 / 2016(only has one leadership pac committee)
http://127.0.0.1:8000/data/candidate/H0OH08029/?tab=about-candidate
https://www.fec.gov/data/candidate/H0OH08029/?tab=about-candidate

(6)click Glossary links

2021-02-01 19:56 UTC, fec-jli commented
Note:
1)The candidate(id=P00009183) returns two rows from api result,
 one is pcc converted to D, another is leadership pac committee,
remove the duplicate committees with same committees_id.
api call: https://fec-dev-api.app.cloud.gov/v1/candidate/P00009183/committees/history/2020/

**Before remove the duplicate committees:**

<img width="646" alt="before_remove_duplicate" src="https://user-images.githubusercontent.com/24395751/106510344-ce139e00-649c-11eb-93f0-04d190696e6b.png">

**After remove the duplicate committees:**

<img width="636" alt="after_remove_duplicate" src="https://user-images.githubusercontent.com/24395751/106510531-0dda8580-649d-11eb-9cca-89b1ae29b53f.png">

The code to pick up distinct committees in data/view.py(start from line 205)
`len_d_cmte = len(committees_d)`
        `committees_leadership_pac.append(committees_d[0])`
       ` for i in range(len_d_cmte):`
           ` if (i + 1) < len_d_cmte and committees_d[i].get("committee_id") != committees_d[i + 1].get("committee_id"):`
               `committees_leadership_pac.append(committees_d[i + 1])`

2)add new sub-class in _glossary.scss:
 `&.term-inline {
      display: inline-block;
    }
`

2021-02-01 23:21 UTC, johnnyporkchops requested changes

2021-02-01 23:21 UTC, johnnyporkchops commented on fec/fec/static/scss/components/_glossary.scss
> +      display: inline-block;
@fec-jli , You should add `margin-bottom u(1rem)` to match the original vertical spacing  on these heading tags

2021-02-02 15:29 UTC, JonellaCulmer commented
@fec-jli Thanks for catching that duplicate committee! This looks really good. 

Would it be possible to move the glossary link + icon before the ":" instead of after?
cc: @dorothyyeager

2021-02-02 16:14 UTC, patphongs requested changes
Thanks @fec-jli, this looks really good. Just once change from me to update the casing of the sponsored leadership PACs heading

2021-02-02 16:14 UTC, patphongs commented on fec/data/templates/partials/candidate/about-candidate.jinja
> +      <h4 class="callout__title term term-inline" data-term="Leadership PAC">Sponsored Leadership PACs:</h4>
The `L` in Leadership should be lowercase. It should look like this: `Sponsored leadership PACs`

2021-02-02 17:24 UTC, johnnyporkchops commented
> @fec-jli Thanks for catching that duplicate committee! This looks really good.
> 
> Would it be possible to move the glossary link + icon before the ":" instead of after?
> cc: @dorothyyeager

@JonellaCulmer , @fec-jli  and I paired on this and although its possible with an :`after` style, it requires removing the colon from the actual text. We agreed this would be a 508  issue to avoid. So we leave the colon before the icon for now.

2021-02-02 17:54 UTC, patphongs approved these changes
Changes look good, thanks @fec-jli

2021-02-02 18:07 UTC, johnnyporkchops approved these changes
Looks great Jun, thanks for taking time to get CSS right!

2021-02-02 20:18 UTC, JonellaCulmer approved these changes
Looks/works great @fec-jli! Thanks for your hard work on this.

2021-02-02 20:25 UTC, merged

2021-02-04 15:57 UTC, fec-jli commented
Thanks Paul correct the data on two tables:
disclosure.cand_cmte_linkage_alternate
disclosure.cand_cmte_linkage 
after today’s materialized view refreshment, I check the front-end on dev, It looks good.
the two examples below, candidate name is a little bit difference:)
a)ROGERS, MICHAEL J — H0MI08042 / C00370791
https://dev.fec.gov/data/candidate/H0MI08042/?tab=about-candidate
https://dev.fec.gov/data/committees/?sponsor_candidate_id=H0MI08042
b)ROGERS, MICHAEL — H2AL03032 / C00439521
https://dev.fec.gov/data/candidate/H2AL03032/?tab=about-candidate
https://dev.fec.gov/data/committees/?sponsor_candidate_id=H2AL03032