Add sponsor link in committee profile
fecgov/fec-cms pull request #4369
Opened 2021-02-08 20:28 UTC by fec-jli

## Summary (required)
Currently, we only show Leadership PAC sponsor name string on about-committee section in committee profile page and don't have the link to candidate profile page.
ex: https://www.fec.gov/data/committee/C00326439/?cycle=2022&tab=about-committee
<img width="544" alt="before" src="https://user-images.githubusercontent.com/24395751/107275714-1e9c7580-6a20-11eb-81e0-07b10f1911ed.png">

after this PR, we change sponsor name to name card and link to candidate profile page.

<img width="480" alt="after" src="https://user-images.githubusercontent.com/24395751/107275965-6b804c00-6a20-11eb-88ee-5d62fd010087.png">

- Resolves #4361

_Include a summary of proposed changes._
1) get sponsor_candidates list from get_committees function in view.py, send to front-end. 
2) modify about-committee.jinja, the sponsor_candidate info will be displayed by the way of name card.

## Impacted areas of the application
committee profile page

List general components of the application that this PR will affect:
data/view.py
about-committee.jinja

## How to test
1) checkout branch
2) point any api
3) pytest
./manage.py test
4) ./manage.py runserver
5) compare local and prod urls:
(1) Presidential candidate:
http://127.0.0.1:8000/data/committee/C00693713/?cycle=2020&tab=about-committee
https://www.fec.gov/data/committee/C00693713/?cycle=2020&tab=about-committee

(2) multi-house:(candidate_id=H6LA04138 and candidate_id=H6IN03229
http://127.0.0.1:8000/data/committee/C00326439/?cycle=2022&tab=about-committee
https://www.fec.gov/data/committee/C00326439/?cycle=2022&tab=about-committee

(3) senate:
http://127.0.0.1:8000/data/committee/C00764878/?cycle=2020&tab=about-committee
https://www.fec.gov/data/committee/C00764878/?cycle=2020&tab=about-committee

(4) multi-senate (but same candidate_id=S0PA00434)
http://127.0.0.1:8000/data/committee/C00455741/?cycle=2016&tab=about-committee
https://www.fec.gov/data/committee/C00455741/?cycle=2016&tab=about-committee

## Reviewer
one developer

2021-02-09 21:08 UTC, JonellaCulmer approved these changes
All looks well to me, @fec-jli. Great work. Thank you.

2021-02-11 14:13 UTC, patphongs requested changes
@fec-jli The functionality is working well, I just have one requested change before approving.

2021-02-11 14:13 UTC, patphongs commented on fec/data/templates/partials/committee/about-committee.jinja
> +            <div class="callout callout--primary">
If we are restricting the width of the candidate callout card, we should restrict it here too by adding `style="width: 100%; max-width: 300px"`

2021-02-11 15:03 UTC, patphongs approved these changes
Thanks for making the change, looks good to me

2021-02-11 21:22 UTC, patphongs commented on fec/data/templates/partials/committee/about-committee.jinja
> +        </tr>
@fec-jli I just noticed one more thing, we don't want to show the "Committee sponsor" section if the `sponsor_candidate_ids` is null. Can you add a check for that on this entire <tr>: {% if sponsor_candidates %} {% endif %}

2021-02-16 15:49 UTC, johnnyporkchops approved these changes
Looks good, we should commit to moving inline styles to a  stylesheet in the next pass of the template code.

2021-02-16 15:54 UTC, merged