Added Administrative termination to the glossary
fecgov/fec-cms pull request #4517
Opened 2021-03-26 14:42 UTC by kathycarothers

Added "administrative termination" to the glossary

Please make sure the end result looks like this:

**Administrative termination** - Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S.C. 30103(d)(2) and 11 CFR 102.4. Administrative termination does not relieve a committee of any legal responsibility for the payment of any outstanding debt or obligations. 

And the links for the statute and regs works too. Thank you.

2021-03-26 16:07 UTC, dorothyyeager reviewed
One small typo to fix - on line 11, need to add an "i" after the "n" in administrative.

Thank you @kathycarothers for tackling this!

2021-03-26 16:14 UTC, kathycarothers commented
I have fixed line 11

2021-03-26 18:30 UTC, dorothyyeager approved these changes
Thank you @kathycarothers Great job!

2021-03-26 18:31 UTC, dorothyyeager approved these changes
Thank you @kathycarothers looks great!

2021-04-01 14:30 UTC, patphongs requested changes
Just one small change, thanks @kathycarothers!

2021-04-01 14:30 UTC, patphongs commented on fec/fec/static/js/data/terms.json
> +    "definition": "Administrative termination is the action taken by the Commission to terminate the reporting obligations of political committees that appear to be inactive in accordance with 52 U.S
Just need to add a space added between the US code and the section number link `52 U.S.C. <a href=...`

2021-04-01 15:37 UTC, patphongs approved these changes
Perfect, thanks @kathycarothers! 

<img width="252" alt="Screen Shot 2021-04-01 at 11 36 53 AM" src="https://user-images.githubusercontent.com/12799132/113318615-a004db80-92de-11eb-8e6f-da0024fa77f9.png">

2021-04-02 14:28 UTC, rfultz approved these changes

2021-04-02 14:28 UTC, merged