[DO NOT MERGE - WIP] 4384 Wagtail upgrade
fecgov/fec-cms pull request #4518
Opened 2021-03-26 19:52 UTC by rfultz

## Summary (required)

- Resolves #issue_number

(Include a summary of proposed changes and connect issue below)

### Required reviewers

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)

## Impacted areas of the application

General components of the application that this PR will affect:

-  

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- 

## System architecture updates (if applicable)

(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a description of those changes here and create a new ticket to update the system diagram)

2021-03-31 21:24 UTC, rfultz commented on fec/extend_admin/wagtailadmin/widgets/chooser.html
> +{% load static %}
All of these are for the new version of Django

2021-03-31 21:25 UTC, rfultz commented on fec/fec/settings/base.py
> +    'wagtail.locales',
New Wagtail

2021-03-31 21:25 UTC, rfultz commented on fec/fec/settings/base.py
> +    'whitenoise.middleware.WhiteNoiseMiddleware',
Required by the new Django and Whitenoise versions

2021-03-31 21:26 UTC, rfultz commented on fec/fec/settings/base.py
> +            'context_processors': [
This solved the error of logging in, closing server, starting server, loading any page at all

2021-03-31 21:26 UTC, rfultz commented on fec/fec/settings/base.py
> +LANGUAGES = (
New for Wagtail & Django versions

2021-03-31 21:27 UTC, rfultz commented on fec/fec/static/scss/base.scss
> +@import "components/responsive-object"; // TODO - remove this? Wagtail 2.8 did away with the responsive-object class
@johnnyporkchops you're way more familiar with the responsive-object classes than I am. Is it safe to remove/change these?

2021-03-31 21:28 UTC, rfultz commented on fec/home/blocks.py
> +    items = blocks.ListBlock(blocks.RichTextBlock(form_classname="nothing"))
New Wagtail change

2021-03-31 21:29 UTC, rfultz commented on fec/home/templates/home/collection_page.html
> +          Get help from the FEC by phone or email
VSC tagged this and one other place for an unusual end of line character

2021-03-31 21:29 UTC, rfultz commented on fec/home/templates/home/resource_page.html
> +            Get help from the FEC by phone or email
This is the other end of line character that VSC didn't like and offered to fix

2021-03-31 21:30 UTC, rfultz commented on requirements.txt
>  PyJWT==1.7.1 # Pinning this version as version 2.0.0 is breaking cg-django-uaa
@lbeaufort with cg-django-uaa 2.1.1, can we unpin PyJWT?

2021-03-31 22:12 UTC, patphongs commented on requirements.txt
>  PyJWT==1.7.1 # Pinning this version as version 2.0.0 is breaking cg-django-uaa
Looks like an upper bound version of PyJWT was pinned inside of `cg-django-uaa`: https://github.com/cloud-gov/cg-django-uaa/blob/110250f119b3d1dbb6f96d8ecc01b696d1632833/setup.py#L93. If that's the case, it shouldn't try and upgrade PyJWT v2.0.1, which is what broke uaa in the first place. I think you're safe to remove.

2021-03-31 22:22 UTC, patphongs commented
@rfultz This was the [QA ticket](https://github.com/fecgov/fec-cms/issues/2305) for content the last time we did a major upgrade of Wagtail. You may be able to use some of the information in that ticket to create a new QA ticket for this upgrade.

2021-04-01 16:13 UTC, patphongs commented on requirements.txt
>  PyJWT==1.7.1 # Pinning this version as version 2.0.0 is breaking cg-django-uaa
Make sense to not touch this pin for now to eliminate extra margins for error in this large PR. @rfultz Can you make a separate ticket to unpin this later?

2021-04-02 22:24 UTC, johnnyporkchops commented on fec/fec/static/scss/base.scss
> +@import "components/responsive-object"; // TODO - remove this? Wagtail 2.8 did away with the responsive-object class
@rfultz The custom  `TV Ad example` styles in here  achieve the intrinsic responsive technique for the TV ad example pages. 
But for RTE embeds,  I will test if adding `WAGTAILEMBEDS_RESPONSIVE_HTML = True` (per Docs) to settings restores that previously default behavior that has been removed.

2021-04-12 06:13 UTC, johnnyporkchops requested changes

2021-04-12 06:13 UTC, johnnyporkchops commented on fec/fec/static/scss/base.scss
> +@import "components/responsive-object"; // TODO - remove this? Wagtail 2.8 did away with the responsive-object class
@rfultz , If we add `WAGTAILEMBEDS_RESPONSIVE_HTML = True` to base;py and change _responsive_object.scss like this, i think it resolves issues with  RTE embeds:
```
.responsive-object {
    position: relative;
    width: 100% !important;
    height: auto !important;

     iframe, object, embed {
       position: absolute;
       top: 0;
       left: 0;
       width: 100%;
      height: 100%;
      }
}
```
This also finally resolves this outstanding issue: https://github.com/fecgov/fec-cms/issues/2212

2021-04-12 14:34 UTC, rfultz commented on fec/fec/static/scss/base.scss
> +@import "components/responsive-object"; // TODO - remove this? Wagtail 2.8 did away with the responsive-object class
Cool. Does this feel like a patch? If so, since it's going away, should we create a ticket to address it more fully? i.e. in a way that doesn't require a special variable to use deprecated functionality

2021-04-12 14:35 UTC, rfultz commented on fec/fec/wagtail_hooks.py
> +        )
Found this solution at https://github.com/wagtail/wagtail/issues/6831#issuecomment-785031388 and it seems to have been exactly what we needed!

2021-04-13 23:04 UTC, johnnyporkchops commented on fec/fec/static/scss/base.scss
> +@import "components/responsive-object"; // TODO - remove this? Wagtail 2.8 did away with the responsive-object class
@rfultz  Likely,  in some future release,  this fallback option will be removed and we could address it differently then. Currently thought, it is a convenient way to add that class to draftail-generated elements, which is (as you know) not as simple as adding class to a template..

2021-04-15 19:30 UTC, patphongs approved these changes
Looks good, thanks for all the fixes @rfultz !

2021-04-15 19:32 UTC, johnnyporkchops approved these changes

2021-04-15 19:47 UTC, merged