Update IE support messaging
fecgov/fec-cms pull request #4649
Opened 2021-05-24 16:59 UTC by patphongs

## Summary

- Resolves #4648 

Updated messaging to indicate that we are no longer supporting Internet Explorer.

### Required reviewers

1 front end and 1 content

## Impacted areas of the application

General components of the application that this PR will affect:

-  Anyone using Internet Explorer

## Screenshots

![Screen Shot 2021-05-24 at 12 50 17 PM](https://user-images.githubusercontent.com/12799132/119382088-9456e500-bc8f-11eb-9fff-5cf806f00176.png)

## How to test

- For content staff: take a look at the screenshot to see if the language in the black banner for no longer support IE looks ok.
- For front end: check out this branch and try it in Internet Explorer. Make sure this banner appears for all versions of Internet Explorer.

2021-05-24 17:27 UTC, rfultz commented
❤️

2021-05-24 17:43 UTC, JonellaCulmer commented
Browser support pages/banners on public websites that no longer support IE:
- https://www.hennepin.us/your-government/open-government/browser-support
- https://www.usajobs.gov/Help/faq/troubleshoot/
- 
![image](https://user-images.githubusercontent.com/31663028/119383900-ee58aa00-bc91-11eb-9e6f-81c301da7d29.png)

2021-05-26 16:54 UTC, patphongs commented
@kathycarothers I've updated the text based on our conversations in Slack. It's ready for you to take a look at the updated screenshot above. Thanks!

2021-05-26 17:01 UTC, kathycarothers approved these changes

2021-06-02 04:26 UTC, johnnyporkchops commented
Internet explorer conditional statements are not supported in `IE10` and above so these tags are ignored. See screenshots showing `IE9` recognizing the statements and showing the warning message, but not `IE10`.

There is a JS alternative, or a CSS 'hack'. I tested both and they seem to work.
JS Option:
```
   function isIE () {
     var myNav = navigator.userAgent.toLowerCase();
     return (myNav.indexOf('msie') != -1 || myNav.indexOf('trident') != -1) ? true : false;
   }
   
   if(isIE()){
     document.getElementById('ie_warning').style.display='block'
   }
 ```

  CSS solution, some may call a 'hack' . 
```

<style>
   #ie_warning {
      display:none;
       }
   @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none), (-ms-high-contrast: black-on-white), (-ms-high-contrast: white-on-black) {  
       #ie_warning {
       display:block;
       }
   }
</style>
  
  ```
  There are a few variations on using CSS to conditionally apply styles in IE only which can be found by googling.
  
  @patphongs , let me know if you want me to push up changes with one of these solution.
 
 
 <hr> 
 
 ##  Screenshots confirming support for conditional comments:
  
  ### IE9 shows warning 
  
![ie9](https://user-images.githubusercontent.com/5572856/120422923-63ce1580-c337-11eb-9a12-0ea5d9b00653.jpg)

### IE10 Does not show warning:

![ie10](https://user-images.githubusercontent.com/5572856/120422965-75172200-c337-11eb-8684-c31a559d7c95.jpg)

2021-06-02 04:27 UTC, johnnyporkchops requested changes

2021-06-02 04:27 UTC, johnnyporkchops commented on fec/fec/templates/base.html
> +    <!--[if lte IE 11]>
Internet explorer conditional statements are not supported in IE10 and above so these tags are ignored. See comment inn conversation for screenshots and alternatives

2021-06-02 14:40 UTC, patphongs commented on fec/fec/templates/base.html
> +    <!--[if lte IE 11]>
Thank you @johnnyporkchops for catching this! I've pushed up a new commit to use the JS conditional you provided instead of the IE HTML conditional statements. Could you please take another look at the homepage, data pages, and wagtail pages to make sure the IE warning isn't showing up unless it's IE?

2021-06-03 12:09 UTC, johnnyporkchops commented
@patphongs The JS solution works to show the warning in IE only on all pages and I can approve it but...

Do you think there it might be  better to use the  CSS solution for something like this?  I did not completely  think through the implementation. Now that I see that the JS snippet has to go in four places, I wonder  if it would more manageable if we could find one css files that gets included everywhere and put it there instead. (It works everywhere if we put it in  `_nav_scss`)

The CSS solution is referred to as a hack by definition I suppose, but using a small hack for dealing with IE seems fitting at this point.

I would strip it down to just detecting `(-ms-high-contrast: none)`, to make sure we don't accidentally target an obscure MS Edge user. That is the one feature not supported above 11. Confirmed by testing this on Edge and IE 10/11 locally with Windows high contrast settings. https://docs.microsoft.com/en-us/previous-versions/hh771830(v=vs.85)

2021-06-03 13:45 UTC, patphongs commented
> The CSS solution is referred to as a hack by definition I suppose, but using a small hack for dealing with IE seems fitting at this point.

@johnnyporkchops I can see your point, but when I look up the CSS version of using `-ms-high-contrast`, it says that it's non-standard and not to use it on production sites: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast. So I feel more inclined to use the JS version even though it's more bulky. Thoughts?

2021-06-03 18:46 UTC, johnnyporkchops commented
> > The CSS solution is referred to as a hack by definition I suppose, but using a small hack for dealing with IE seems fitting at this point.
> 
> @johnnyporkchops I can see your point, but when I look up the CSS version of using `-ms-high-contrast`, it says that it's non-standard and not to use it on production sites: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast. So I feel more inclined to use the JS version even though it's more bulky. Thoughts?

That info ^^ is why it works, because it is only supported in <= IE11. So we are not actually trying to use the feature, just detecting for non-modern browsers that support it.

2021-06-03 18:49 UTC, johnnyporkchops commented
https://stackoverflow.com/questions/18907131/detecting-ie11-using-css-capability-feature-detection

2021-06-07 20:24 UTC, johnnyporkchops approved these changes
Tested in IE 11/10 and Edge and modern browsers works as expected. 
Even tested in Edge with Windows ms-high-contrast settings enabled and does not show in Edge. 
Thanks Pat!

2021-06-07 21:09 UTC, merged