Activate state election cards on election profile pages
fecgov/fec-cms pull request #4655
Opened 2021-05-25 19:39 UTC by patphongs

## Summary

- Resolves #4654 

Activate state election cards and links them on the election profile pages

### Required reviewers

1 front end and 1 UX

## Impacted areas of the application

General components of the application that this PR will affect:

-  Senate and house election profile pages

## Screenshots

![Screen Shot 2021-05-25 at 3 37 43 PM](https://user-images.githubusercontent.com/12799132/119558282-339ed980-bd6f-11eb-8293-11cec2a61373.png)

## How to test

- checkout this branch
- `./manage.py runserver`
- Go to any election profile page. Ex: http://localhost:8000/data/elections/house/CA/01/2022/
- Check that the All state elections card is active and links back to the correct state and year search on the election search page

2021-05-25 19:48 UTC, rfultz approved these changes
Works well!
Functionality is approved, but I have design/content questions I'll add to the thread

2021-05-25 19:52 UTC, rfultz commented
Works well!

Is it weird that we have three buttons across the top and they're three different colors? I thought maybe it was a current-active-inactive thing but no.

Also, why is it "All House elections" but "All - [state name] state elections"? I'd like to remove the… hyphen? dash? (It's not an emdash and doesn't look like an endash)

2021-05-25 19:53 UTC, rfultz requested changes
Works well!

It doesn't like medium-width browser windows

2021-05-25 20:21 UTC, patphongs commented
Thanks @rfultz, I've logged an issue with the medium-width browsers. This seems to be a thing for pages like this with a left nav, it doesn't stack well and some content is cut off. https://github.com/fecgov/fec-cms/issues/4656

2021-05-26 13:37 UTC, JonellaCulmer commented
Great catches!

> Is it weird that we have three buttons across the top and they're three different colors? I thought maybe it was a current-active-inactive thing but no.

There should only be two colors. As you said, an active and inactive state. @patphongs Let me know if you need anything from me. We should probably resolve this while we're messing with buttons, right?

> Also, why is it "All House elections" but "All - [state name] state elections"? I'd like to remove the… hyphen? dash? (It's not an emdash and doesn't look like an endash)

I agree. We should drop the hyphen. @dorothyyeager just in case you have thoughts.

2021-05-26 13:51 UTC, dorothyyeager commented
I concur, drop the hyphen.

2021-05-26 14:06 UTC, patphongs commented
Thanks for your reviews @JonellaCulmer @rfultz. I've updated by removing the hyphen and using the primary colors for the state card. Could you have another look please?

![Screen Shot 2021-05-26 at 10 03 35 AM](https://user-images.githubusercontent.com/12799132/119673821-b07e9180-be09-11eb-86fc-562e332228e2.png)

2021-05-26 19:42 UTC, JonellaCulmer commented
@patphongs It looks great with the colors fixed. A couple things I noticed:
- The election icons, for the state card and inactive all house card are two different sizes. Can you make the inactive election icon the same size as the state card?
- We use the default language "....state elections" for the state cards, but not all are states. Like Guam or Northern Mariana Islands. Can we customize the language for certain places if we know their not states? And depending on the year, most of those places only have the one election going on.  cc: @dorothyyeager @kathycarothers Let me know if you have thoughts on this.
Example:
<img width="1129" alt="Screen Shot 2021-05-26 at 10 37 39 AM" src="https://user-images.githubusercontent.com/31663028/119721249-f141cf00-be38-11eb-9e2e-4ba766908a13.png">

2021-05-26 20:05 UTC, dorothyyeager commented
For the territories, you are right @JonellaCulmer - usually they only have one (federal) election going on and sometimes it's at weird times. For example, I think Puerto Rico does their elections in odd-numbered years. (Unless the plural refers to primaries and generals.) 

Maybe we just take out the word "state" to resolve the territory part of this? I kind of find it confusing anyway considering we are talking federal elections.

2021-05-26 22:29 UTC, patphongs commented
> Maybe we just take out the word "state" to resolve the territory part of this? I kind of find it confusing anyway considering we are talking federal elections.

@dorothyyeager @JonellaCulmer I was thinking to remove the word "state" as well, that's certainly a simpler solution.

As for the "All [state_or_territory_name] elections" card, the wording on that is difficult because there's multiple possibilities of what we'll show depending on year. The fact that we will sometimes show the presidential election when it's a presidential year is problematic because that's a federal election, not a state specific one, so we can't really call it, for example, a California election.

- Possibility 1 - Display president, house, and senate elections. Ex: https://www.fec.gov/data/elections/?cycle=2020&state=AL
- Possibility 2 - Display senate and house elections. Ex: https://www.fec.gov/data/elections/?cycle=2018&state=AL
- Possibility 3 - Display only house elections. Ex: https://www.fec.gov/data/elections/?cycle=2006&state=AL

If we cross that hurdle, this is another thing that I'm not sure about. The plural of the word "elections", doesn't sound grammatically correct in the singular if we use the word "all". Any suggestions?

2021-05-26 22:32 UTC, patphongs commented
> The election icons, for the state card and inactive all house card are two different sizes. Can you make the inactive election icon the same size as the state card?

Done! Pushed up a commit to update this.

2021-05-27 12:32 UTC, dorothyyeager commented
@patphongs The only thing I can think of is to ditch "all" and just say "Northern Marianas elections" but as you pointed out, President is a nationwide election (although each state/territory administers it in their locality). Maybe "Northern Marianas federal ballot"? But that's clunkier.

2021-05-27 14:34 UTC, patphongs commented
After discussing with @JonellaCulmer @dorothyyeager @kathycarothers, we've decided to update the card names to include the word "federal". This is what they'll look like: "All federal [state_or_territory_name] elections", "All federal House elections", and "All federal Senate elections". 

@JonellaCulmer @rfultz It's all ready for your review again, thanks!

2021-05-28 15:05 UTC, JonellaCulmer approved these changes
Everything looks great. Thanks, @patphongs

2021-06-03 13:23 UTC, rfultz approved these changes
Looks good!

2021-06-03 13:23 UTC, merged