Fix disclaimer text
fecgov/fec-cms pull request #4658
Opened 2021-05-25 22:23 UTC by patphongs

## Summary

- Resolves #4657 

Fix the incomplete disclaimer text at the bottom of the committee profile page disbursements datatable.

### Required reviewers

1 front end and 1 UX

## Impacted areas of the application

General components of the application that this PR will affect:

-  Committee profile pages

## Screenshots

![Screen Shot 2021-05-25 at 6 20 58 PM](https://user-images.githubusercontent.com/12799132/119576046-03166a00-bd86-11eb-84a6-feab63fab835.png)

## How to test

- Check out this branch
- ./manage.py runserver
- Go to any committee profile page disbursements section and click on the "Recipient name" tab. Look at the disclaimer text below the table to make sure it's complete and links correctly.

2021-06-01 14:29 UTC, rfultz requested changes
I'm getting an error when I click the link. ?
![image](https://user-images.githubusercontent.com/26720877/120340681-40b64e00-c2c4-11eb-85b8-374db95ade8b.png)

2021-06-01 14:33 UTC, rfultz commented on fec/data/templates/macros/disclaimer.jinja
> +    <a href="/{{ type }}/?committee_id={{ id }}&two_year_transaction_period={{ cycle }}">access the list of itemized transactions.</a></p>
The link takes me to `/disbursements…` and is broken, but `/data/disbursements…` seems to be good

2021-06-01 15:06 UTC, lbeaufort commented on fec/data/templates/macros/disclaimer.jinja
> +    <a href="/{{ type }}/?committee_id={{ id }}&two_year_transaction_period={{ cycle }}">access the list of itemized transactions.</a></p>
@patphongs would it be more semantic to name the URL in urls.py and reference it by name, like in the docs: https://docs.djangoproject.com/en/dev/ref/templates/builtins/#url

2021-06-02 20:24 UTC, patphongs commented
Good catches @rfultz @lbeaufort, pushed up another commit using `url` so that I'm not hardcoding the root path.

2021-06-03 13:12 UTC, rfultz approved these changes
Looks good to me!

2021-06-03 16:13 UTC, merged