Feature/3934 new tv ad background
fecgov/fec-cms pull request #4715
Opened 2021-06-16 21:34 UTC by johnnyporkchops

## Summary
A new TV ad example background image
Add scss to _responsiveA_object.scss with comments showing html structure needed to use it

- Resolves #3934

### Required reviewers
One front end, and @djgarr 

## Impacted areas of the application

modified:   fec/static/scss/components/_responsive-object.scss
new-file:    fec/fec/static/img/new-tv-bkgd-wide.png

## Screenshots

![new_tv_ex](https://user-images.githubusercontent.com/5572856/122296860-e4a91780-cec8-11eb-8d85-78a439400111.gif)

## How to test

**@djgarr or content/UX team:**
- Test on feature by viewing/editing  https://fec-feature-cms.app.cloud.gov/test-new-tv-ad-example/
- Or create a new ExamplePage and test adding a TV ad example using same html as the above page

**Developer:**
- pull branch `feature/3934-new-tv-ad-background`
- npm run build-sass
- create a new page of type: ExamplePage
- Add html block with structure shown in comment for /New TV Ad example in `_responsive_object.scss`
- You can use this video iff you like: `https://www.youtube.com/embed/ppHBaPBT3gU`
- View page at different screen sizes

2021-06-17 13:03 UTC, djgarr approved these changes
Looks good to me. Thanks again!

2021-06-22 15:30 UTC, rfultz requested changes
Works well for me!

Could we lose or change the "new" part?

2021-06-22 15:30 UTC, rfultz commented on fec/fec/static/scss/components/_responsive-object.scss
> +#new-tv-ad-example {
I'm not loving the "new" in the class name (or in general) because it's only new for now and "new" doesn't really describe its function, goal, or appearance. Even something like "tv-ad-example-2021" would be more descriptive and evergreen

2021-06-22 16:55 UTC, johnnyporkchops commented on fec/fec/static/scss/components/_responsive-object.scss
> +#new-tv-ad-example {
Actually, it should probably be a class too, in case they need to use more than one on a page (in addition to other reasons that a class is preferable)

2021-06-22 17:29 UTC, rfultz approved these changes
Woo hoo! Thanks, John!

2021-06-22 17:29 UTC, merged