Add two glossary terms
fecgov/fec-cms pull request #4814
Opened 2021-08-04 14:31 UTC by djgarr

Adds glossary terms for "Cooperatives" and "Single candidate independent expenditure filer" (refer to https://github.com/fecgov/fec-cms/issues/4793#issuecomment-886656974 for definitions)

2021-08-04 18:29 UTC, dorothyyeager requested changes
One minor change and one question/possible change

2021-08-04 18:29 UTC, dorothyyeager commented on fec/fec/static/js/data/terms.json
> +  },
Same thing on this PR
1. Make state lower case s
2. Should Cooperatives be singular? (I vote yes but check with @rfultz and @JonellaCulmer for design reasons.)

2021-08-04 19:38 UTC, djgarr commented on fec/fec/static/js/data/terms.json
> +  },
Change made to "state"

2021-08-05 12:50 UTC, JonellaCulmer commented on fec/fec/static/js/data/terms.json
> +  },
@dorothyyeager No issue with cooperatives being single. The vast majority of our glossary terms are singular. I'd go so far as to recommend we determine that the other plural terms don't need to be changed to singular as well. 
I found: `communication costs`, `communication filers`, `federal funds`(think it might sound weird in the singular), `levin funds`(levin fund sounds weird to me), `operating expenditures`, and `reports, designations and statements`

2021-08-05 13:00 UTC, djgarr commented on fec/fec/static/js/data/terms.json
> +  },
Removed the S from "Cooperatives"

2021-08-05 13:08 UTC, dorothyyeager commented on fec/fec/static/js/data/terms.json
> +  },
@JonellaCulmer Let's make a separate ticket for "Ensuring glossary terms are consistent grammar-wise"?

2021-08-05 13:08 UTC, dorothyyeager approved these changes
Approved. Thanks @djgarr

2021-08-06 17:52 UTC, JonellaCulmer commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
Is there a reason why we say "...committees" for `com_type_text` and "...filer" for `com_type_glossary`?

2021-08-09 13:58 UTC, patphongs commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
I think the text for the committee type that appears on the page (com_type_text) should match the actual glossary term (com_type_glossary). What are your thoughts @djgarr?

2021-08-09 14:05 UTC, dorothyyeager commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
One thing I would note is that sometimes we use singular and sometimes we use plural on H4CC pages. Whatever makes sense for the sentence.

2021-08-09 14:14 UTC, djgarr commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
I was going off the original ticket terms for the glossary items. My preference would be to stick as close to the approve text and forms as possible, which would be changing the word filer to committee. That said, would OGC need to review the change?

2021-08-09 14:21 UTC, dorothyyeager commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
Probably.

2021-08-11 19:31 UTC, dorothyyeager approved these changes
Thank you David for working with OGC on this.

2021-08-17 13:54 UTC, patphongs commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
@djgarr Was there a consensus on updating the text to match the glossary term?

2021-08-17 13:55 UTC, patphongs commented
> @djgarr @patphongs Can we close this PR since another PR was created and merged?

@djgarr @JonellaCulmer We'll still need this glossary PR for the CMS. I added a [comment](https://github.com/fecgov/fec-cms/pull/4814#discussion_r690394684) above about what we'd like to do with the text and term matching up.

2021-08-17 14:23 UTC, patphongs commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
@djgarr Looks like the glossary term was removed. If so, can you removed them from the `com_type_text` and `com_type_glossary` in the views.py?

2021-08-17 15:54 UTC, patphongs commented on fec/data/views.py
> +        com_type_glossary = 'Single candidate independent expenditure filer'
@djgarr I went ahead and made this change, as I know you're super busy today.

2021-08-18 14:23 UTC, JonellaCulmer commented on fec/data/views.py
> +        com_type_glossary = 'Cooperatives'
@patphongs @djgarr If it's singular in the /terms file, should it be singular here?

2021-08-18 14:38 UTC, JonellaCulmer approved these changes
Looks good.

2021-08-18 14:39 UTC, merged