Update glossary to add foreign national terms
fecgov/fec-cms pull request #5044
Opened 2022-01-27 20:36 UTC by djgarr

## Summary (required)

Adds two terms to glossary

https://docs.google.com/spreadsheets/d/1iSHhncHt8JCzYrh_UEHmyhoy3sKEpAnNNspCYdS188g/edit#gid=0 (see highlighted terms)

- Resolves #5042

2022-01-27 20:50 UTC, patphongs requested changes

2022-01-27 20:50 UTC, patphongs commented on fec/fec/static/js/data/terms.json
> +    "definition": "An individual lawfully admitted for permanent residence is someone who has been granted authorization to live and work in the United States on a permanent basis. As proof of that s
@djgarr When there are quotations as part of the text, it needs to be escaped with a backwards slash. Like this `...called a \"Green Card.\""`. After that change, it'll work, thanks!

2022-01-27 20:55 UTC, djgarr commented on fec/fec/static/js/data/terms.json
> +    "definition": "An individual lawfully admitted for permanent residence is someone who has been granted authorization to live and work in the United States on a permanent basis. As proof of that s
Text updated

2022-01-27 21:58 UTC, dorothyyeager approved these changes
Approved from content team perspective. Thanks David, nice job!

2022-01-28 14:23 UTC, patphongs approved these changes
Looks good, thanks @djgarr !

<img width="267" alt="Screen Shot 2022-01-28 at 9 22 48 AM" src="https://user-images.githubusercontent.com/12799132/151563287-e5972819-bf9e-430c-ada4-ef48e4bcb203.png">

2022-01-28 14:23 UTC, merged