Contributions across time for House/Senate Overview page
fecgov/fec-cms pull request #5166
Opened 2022-04-15 01:17 UTC by johnnyporkchops

## Summary 

Chart for viewing contributions by two-year periods going back from the current election year

- Resolves #5034

Related issues:
Methodology: https://github.com/fecgov/fec-cms/issues/5090

(Include a summary of proposed changes and connect issue below)

### Required reviewers

Two frontend (ideally) , one UX

## Impacted areas of the application

	modified:   data/templates/house-senate-overview.jinja
	modified:   data/templates/partials/house-senate-overview/election-data.jinja
	modified:   data/views.py
	new file:   fec/static/js/pages/contributions_across_time.js
	new file:   fec/static/scss/widgets/house-senate-overview.scss

<hr>

## Screenshots
### Responsive:

![cat_reponsive](https://user-images.githubusercontent.com/5572856/163502480-58e0311a-bb47-4844-8b15-64c48d58781f.gif)

<hr>

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

- checkout branch and `npm run build`
- go to http://127.0.0.1:8000/data/elections/house/ and http://127.0.0.1:8000/data/elections/senate/
- test the feature
- Responsive: The meter bars are set to a percentage width and everything stays on one line until you resize to `<400px` or `Iphone SE` in the Chrome responsive inspector at which point the items stack.

2022-04-27 16:52 UTC, rfultz requested changes
Solid! A few tiny things, questions, and 👍🏼

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/house-senate-overview.jinja
> +var context = {{ context_vars | to_json | safe }};
Ooooh I like it

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/house-senate-overview.jinja
> +<script src="{{ asset_for_js('contributions_across_time.js') }}"></script>
the underscores go against the convention of using dashes for js and css

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/macros/cycle-select.jinja
>            <label for="{{id}}-cycle">Beginning</label>
Is the label being removed from the page? I don't see it on https://fec-feature-cms.app.cloud.gov/data/elections/senate/#contributions-over-time

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/macros/cycle-select.jinja
>            <label for="{{id}}-cycle">Ending</label>
Is the label being removed from the page? I don't see it on https://fec-feature-cms.app.cloud.gov/data/elections/senate/#contributions-over-time

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/macros/cycle-select.jinja
> +          <select id="{{id}}-cycle" class="js-min-period-select" name="cycle" data-cycle-location="query" data-period=
On https://fec-feature-cms.app.cloud.gov/data/elections/senate/#contributions-over-time, the id is evaluating to "-cycle" and there are two elements (`<select>`) with the same id

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/macros/cycle-select.jinja
> +          <select id="{{id}}-cycle" class="js-max-period-select" name="cycle" data-cycle-location="query" data-period=
On https://fec-feature-cms.app.cloud.gov/data/elections/senate/#contributions-over-time, the id is evaluating to "-cycle" and there are two elements (`<select>`) with the same id

2022-04-27 16:52 UTC, rfultz commented on fec/data/templates/partials/house-senate-overview/sidebar-nav.jinja
> +            {#  <li><a href="#money-raised-accross-elections">Money raised accross {{ office | title }} elections</a></li>
Any reason to keep these—are we bringing them back soon? (if so, can we change to 'across')

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +      let subConcat = `${sub}thorized_committee`;
😆 I was wondering what was going on, then saw the comment

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +      // Could be done more efficiently with URLSearchParams(), but since MS Edge-legacy does not support, we'll do this for now
Excellent. Well, not excellent that we have to, but excellent that the comment explains why

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +            <div role="cell" class="simple-table__cell js-total-value t-mono-stacked-currency"><a href=${totalUrl}>${textValue}</a></div>
Does `<a href=${totalUrl}>` output with the href quoted? (If not, we should in case a space sneaks into the path and breaks the link)

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +    let meterElement = periodWrapper.getElementsByTagName('meter');
Any worries about picking up other <meter> elsewhere, like if we add this to another page or add other features to this page?

The variable is meterElement (singular) but `getElementsByTagName` will return all of them, right?

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +     let beginning = action == 'min' ? e.target.value : this.minYearControl.value;
I'm curious what these two lines are doing—checking for an action of 'min' and using that element's value or otherwise grabbing the value from minYearControl? So, grab min's value if it was changed or if it wasn't changed?

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +      // else if (response.type == 'cors') throw new Error('CORS error');
I think this is my fault. We should probably remove it

2022-04-27 16:52 UTC, rfultz commented on fec/fec/static/js/pages/contributions_across_time.js
> +      // TODO - handle catch
I think this is my fault. We should probably remove it but that feels wrong. Thoughts?

2022-04-27 16:52 UTC, rfultz commented on fec/data/views.py
> +    office_codes = {
Oh, I didn't think about us needing the reverse…
Can we make the quotes consistent?
Should we add P?

2022-04-27 17:07 UTC, patphongs commented on fec/data/templates/house-senate-overview.jinja
> +<script src="{{ asset_for_js('contributions_across_time.js') }}"></script>
@johnnyporkchops, if you're going to rename this file, could you rename it to something more generic, maybe "elections-overview.js"? I'm hoping to also include the code for the all elections totals table within the same JS file, so we don't need to have separate files per feature.

2022-04-27 17:20 UTC, JonellaCulmer commented
Cannot view locally, so any tips are appreciated. The following review is based on your screenshot/gif.

For the current two-year period, the bar chart needs to have a different appearance to clarify and reinforce that the cycle is currently in progress. This detail is very important and helps to put the data into context when comparing to previously completed cycles. I consider this detail a blocker to completion. 

The speed with which the columns populate are a bit slow - can we match the speed of the bar charts in the [raising/spending summaries](https://www.fec.gov/data/raising-bythenumbers/). 

The kerning is tight on the section headers. 

I don't want to introduce a third bar chart style: the slightly rounded corners. We need to mimic the style of the bar charts in the raising and spending summaries (but larger), or in the Who's raising the most charts. I'd prefer the latter. But both can be found on the Raising and Spending by the numbers pages: https://www.fec.gov/data/raising-bythenumbers/

2022-04-28 05:12 UTC, johnnyporkchops commented on fec/data/templates/macros/cycle-select.jinja
>            <label for="{{id}}-cycle">Ending</label>
@rfultz I ended up not using this macros for the feature, so we can remove it.

2022-04-28 05:12 UTC, johnnyporkchops commented on fec/data/templates/macros/cycle-select.jinja
>            <label for="{{id}}-cycle">Beginning</label>
@rfultz I ended up not using this macros for the feature, so we can remove it.

2022-04-28 05:14 UTC, johnnyporkchops commented on fec/fec/static/js/pages/contributions_across_time.js
> +    let meterElement = periodWrapper.getElementsByTagName('meter');
@rfultz Good question, I thought it was OK since its in the context of the periodWrapper element.

2022-04-28 05:21 UTC, johnnyporkchops commented on fec/fec/static/js/pages/contributions_across_time.js
> +     let beginning = action == 'min' ? e.target.value : this.minYearControl.value;
@rfultz , It determines which select was chosen for the math.min/max check so it can transpose min/max in call to data if year  of min select is  > year  of max select

2022-04-28 05:29 UTC, johnnyporkchops commented on fec/data/views.py
> +    office_codes = {
@patphongs , @rfultz I  left it this way in case the answer to Pat's question is yes. 
The reverse is also still in the `def elections` view but I don't think we need it in both places now that we added the new `def elections_president`  view when we created `house_senate overview` templates.

2022-04-28 05:35 UTC, johnnyporkchops commented on fec/data/templates/house-senate-overview.jinja
> +<script src="{{ asset_for_js('contributions_across_time.js') }}"></script>
@pat, I will rename it as you suggested. I am wondering though if the other complicated  features on the page, (like Treemap) will be better off in their own  JS file so maybe eventually we can rename this one less generic, and more specific to the features it applies to (at this point it would be the across-time and the feature you are adding)

2022-04-28 23:24 UTC, johnnyporkchops commented on fec/fec/static/js/pages/contributions_across_time.js
> +      // else if (response.type == 'cors') throw new Error('CORS error');
Can we leave this in here for now as a TODO?

2022-04-28 23:24 UTC, johnnyporkchops commented on fec/fec/static/js/pages/contributions_across_time.js
> +      // TODO - handle catch
@rfultz Can we leave this in here for now as a TODO?

2022-05-02 17:28 UTC, rfultz approved these changes
Inconsistent quotes (single and double in same file and on the same lines) but looks good for a merge not intended to be public (methodology work, etc)

2022-05-02 17:28 UTC, rfultz commented on fec/data/templates/house-senate-overview.jinja
> +<script src="{{ asset_for_js('elections-overview.js') }}"></script>
Excellent!

2022-05-02 17:28 UTC, rfultz commented on fec/data/views.py
> +    office_codes = {
Does Python handle single and double quotes differently—any reason we're using both right next to each other?

2022-05-02 17:37 UTC, JonellaCulmer commented
@johnnyporkchops This is looking really great! The only thing I found, that I didn't see because I couldn't view it locally for my first review, is the wrapping of the "footnote"-type language. The button stacks underneath the text at smaller widths and I don't think we want that. For other charts with the footer language, there's a line break about halfway across the feature, and the buttons stack to the right. Here's an example: https://www.fec.gov/data/raising-bythenumbers/

2022-05-03 18:14 UTC, patphongs commented
Merging this in since the disclaimer text and methodology button will be taken care in #5131

2022-05-03 18:14 UTC, merged