All elections totals table
fecgov/fec-cms pull request #5196
Opened 2022-05-05 17:06 UTC by patphongs

## Summary

- Resolves #5131 

All elections totals datatable using the new `/candidates/totals/aggregates/` endpoint.

### Required reviewers

1 front-end, 1 back-end, 1 UX

## Impacted areas of the application

General components of the application that this PR will affect:

-  House and Senate elections overview pages

## Screenshots

<img width="956" alt="Screen Shot 2022-05-05 at 1 00 42 PM" src="https://user-images.githubusercontent.com/12799132/166974969-53746dd0-def4-476b-a126-39becd5eb413.png">
<img width="951" alt="Screen Shot 2022-05-05 at 12 51 43 PM" src="https://user-images.githubusercontent.com/12799132/166974970-36990d64-bfa5-43b7-8cee-2ce170d3aa40.png">

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
feature/5034-contributions-across-time | [link](https://github.com/fecgov/fec-cms/pull/5166)

## How to test

- checkout this branch
- `cd fec && ./manage.py runserver`
- `npm run build`
- Go to the elections overview pages:
   - [Senate all elections totals table](http://localhost:8000/data/elections/senate/#totals-for-all-elections)
   - [House all elections totals table](http://localhost:8000/data/elections/house/#totals-for-all-elections)

2022-05-05 18:47 UTC, cnlucas approved these changes
Thanks for pairing!

2022-05-13 14:50 UTC, JonellaCulmer commented
@patphongs Just a couple comments:
- There is a bold blue line missing from the top of the table. It should run along the length of feature and sit just above the column headers. 
![Screen Shot 2022-05-13 at 10 49 14 AM](https://user-images.githubusercontent.com/31663028/168309360-c8f03183-fcb9-452d-b014-f5c766c4adba.png)

- The table looks different from the contributions across time feature. It's not contained within the gray background and the description "Compare the money..." is in bold.
- Also, should we edit the text to say "Compares..."? That's my typo - sorry I didn't see that sooner.

2022-05-14 05:31 UTC, johnnyporkchops requested changes
Works/Looks great, all the sorting and responsive behavior is working perfectly! Just a few html edits to for display.

2022-05-14 05:31 UTC, johnnyporkchops commented on fec/data/templates/partials/house-senate-overview/election-data.jinja
> +         <table id="election-totals-results"
@patphongs You could add `simple-table u-no-border` to table class  to get the top border that Jonella mentioned (`u-no-border` removes a double bottom border)

2022-05-14 05:43 UTC, johnnyporkchops commented on fec/data/templates/partials/house-senate-overview/election-data.jinja
>        <div id="money-raised-accross-elections" class="entity__figure row">
Uncomment the anchor link to this ID in `sidebar-nav.jinja`

2022-05-14 05:55 UTC, johnnyporkchops commented on fec/fec/static/js/pages/elections-overview.js
> +
Nice job figuring out how to combine the two scripts!

2022-05-14 05:56 UTC, johnnyporkchops commented on fec/fec/static/js/pages/elections-overview.js
> +
Nice job figuring out how to combine the two scripts!

2022-05-16 13:54 UTC, patphongs commented
Thanks @johnnyporkchops and @JonellaCulmer for all of the reviews. This is ready for you to take a look again.

2022-05-16 14:44 UTC, johnnyporkchops commented on fec/data/templates/partials/house-senate-overview/election-data.jinja
> +         <p class="t-sans t-bold t-low-height">Compares the money raised, spent, cash on hand and debts by {{ office | title }} election</p>
this should not be bold  . We say "comparing"  in  the  across  time  feature

2022-05-16 16:32 UTC, patphongs commented
> @JonellaCulmer We say "comparing" on across time feature. We should change that to match too, right?

Thanks @johnnyporkchops, as agreed upon by the content team, we're changing this to be "comparing" throughout the house and senate overview page

2022-05-16 18:09 UTC, johnnyporkchops approved these changes

2022-05-16 18:19 UTC, merged