5215 house and senate overview totals
fecgov/fec-cms pull request #5443
Opened 2022-10-17 14:26 UTC by rfultz

## Summary

- Resolves #5215 

Quite a few changes to [/data/elections/house/](http://127.0.0.1:8000/data/elections/house/) and [/data/elections/senate/](http://127.0.0.1:8000/data/elections/senate/)

### Required reviewers

Front-end and UX?

## Impacted areas of the application

The House & Senate overview pages

## Screenshots

Before:
![image](https://user-images.githubusercontent.com/26720877/196201798-dd459d04-508e-4135-bc7e-209ba7f4bee6.png)

This PR:
![image](https://user-images.githubusercontent.com/26720877/196201906-38e047b2-ae48-457c-ae56-768909514eb9.png)

## Related PRs

None

## Known TODOs

- Look & feel of the summary section (and maybe the others)
- Values and formulas verification (Paul?)
- Layouts for the in-between sizes
- Organization of the rest of the page—section titles, tab organization, flags
- Specific TODOs in the code—features, etc
- Testing w/ non-Chromium browsers

## How to test

- pull the branch
- `npm i`
- `npm run build`
- `./manage.py runserver`
- [House elections page](http://127.0.0.1:8000/data/elections/house/)
   - initial load works?
   - changing the election year pull-down works?
   - changing tabs works?
   - changing tabs or years, copy the URL, paste it back in. Does it work as expected?
   - are the other tabs' content broken?
- [Senate elections page](http://127.0.0.1:8000/data/elections/senate/)
   - initial load works?
   - changing the election year pull-down works?
   - changing tabs works?
   - changing tabs or years, copy the URL, paste it back in. Does it work as expected?
   - are the other tabs' content broken?

2022-10-24 19:12 UTC, patphongs requested changes
Noticed that the query statements should be tweaked slightly to display the correct totals.

2022-10-24 19:12 UTC, patphongs commented on fec/fec/static/js/pages/house-senate-overview-summary.js
> +        `${theURL}&aggregate_by=office`,
It appears that this is concatenating two `aggregate_by` parameters into the same call. But you can only pass one in a single call. The total raised, spent, and cash on hand dollar figures should be coming from a call that passes `aggregate_by=office`. The party breakdown for  raised, spent, and cash on hand should be coming from a call that passes `aggregate_by=office-party`. 

The dollar figures in this feature should match the dollar figures that we have in the summary [raising by the numbers](https://www.fec.gov/data/raising-bythenumbers/) and summary [spending by the numbers](https://www.fec.gov/data/spending-bythenumbers/) pages.

2022-10-25 14:43 UTC, rfultz commented on fec/fec/static/js/pages/house-senate-overview-summary.js
> +        `${theURL}&aggregate_by=office`,
Oooh, good catch!
Aggregate totals is using `/candidates/totals/by_office/` and `…by_party/`
but the ticket attached to this says to use `/candidates/totals/aggregates/`.

Should they be using different endpoints?

2022-10-26 17:42 UTC, patphongs commented on fec/fec/static/js/pages/house-senate-overview-summary.js
> +        `${theURL}&aggregate_by=office`,
Eventually `/candidates/totals/by_office/` and `/candidates/totals/by_party/` will be deprecated since we found a better and cleaner way to do the totals with the `/candidates/totals/aggregates/` endpoint. I'll file a ticket for that later.

2022-10-26 20:09 UTC, rfultz commented on fec/fec/static/js/pages/house-senate-overview-summary.js
> +        `${theURL}&aggregate_by=office`,
When I look at the values coming back from those endpoints, the values aren't the same. Looking specifically at S, 2020, Dem, total receipts,

`/candidates/totals/by_office/by_party/?election_full=true&election_year=2020&sort_hide_null=false&sort_null_only=false&per_page=20&sort_nulls_last=false&office=S&page=1&api_key=`
returns `1245650818.65`

`/candidates/totals/aggregates/?election_full=true&is_active_candidate=true&per_page=10&aggregate_by=office-party&election_year=2020&office=S&api_key=`
returns `1238433907.94`

2022-10-27 19:28 UTC, patphongs commented on fec/fec/static/js/pages/house-senate-overview-summary.js
> +  };
@rfultz The total raised should actually be `total_receipts` and not the aggregate of all of these put together. This is the discrepancy we're seeing in the raising data.

2022-11-17 17:04 UTC, JonellaCulmer commented on fec/data/templates/partials/house-senate-overview/section-summary.jinja
> +                    <h2 class="description js-value-large-desc">raised by {{ office | title }} candidates</h2>
I think we can drop House from these so that the cash on hand one doesn't wrap.

2022-11-18 19:53 UTC, JonellaCulmer commented
@rfultz Great work!!! Just a few odds and ends:
1. Need a bit more breathing room between section headers and edit the language in the Senate/House button. Harder to distinguish between the different sections currently. 
<img width="271" alt="Screen Shot 2022-11-17 at 12 06 28 PM" src="https://user-images.githubusercontent.com/31663028/202520158-02c8ff5c-9c9e-4768-bd11-fb03e182be9c.png"> 
Example on [H4CC page](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/). 

2. Dem blocks are still red on load or refresh.

3. Adjust intro text on election summary feature to say: "Comparing total money raised, spent and cash on hand, by party." (Since we removed "remaining" from the cash on hand section)

4. Can we tighten up the space between the bottom line and the bottom help text and methodology button?
Before
<img width="759" alt="Screen Shot 2022-11-18 at 2 47 29 PM" src="https://user-images.githubusercontent.com/31663028/202789733-c0026382-a600-4179-91e1-05afaae2f22b.png">

After ([As seen on Raising browse data page](https://www.fec.gov/data/browse-data/?tab=raising)):
<img width="749" alt="Screen Shot 2022-11-18 at 2 45 57 PM" src="https://user-images.githubusercontent.com/31663028/202789529-e57b2ed8-d97f-4b03-8759-b6f4e2416c77.png">

5. Should we open a separate ticket for this? There are weird blocks appearing at the bottom of House candidate contributions over time and totals for all House elections features. And no padding between text and methodology button
<img width="834" alt="Screen Shot 2022-11-17 at 12 05 45 PM" src="https://user-images.githubusercontent.com/31663028/202790602-4784081e-c5d8-4be7-a08a-d969f260bce5.png">

2022-12-06 20:29 UTC, patphongs approved these changes
Thanks @rfultz, looks good now

2022-12-06 20:29 UTC, merged