Sort MUR by case_no
fecgov/fec-cms pull request #5601
Opened 2023-02-06 17:38 UTC by johnnyporkchops

## Summary
Make MURS sortable by case number at:
https://www.fec.gov/data/legal/search/murs/ --OR--
https://www.fec.gov/data/legal/search/enforcement/ 

- Resolves #5261

### Future work: 
This should work for AOs and possibly ADR/AFS. If we want to repurpose it for these, I recommend we remove the JS from the MURs template and revise the script to work for all of them and put it under /`js/pages` or `/js/modules`. If that is possible, given the differences in those results-tables.

### Required reviewers

One frontend, one backend (@fec-jli ), one UX

## Impacted areas of the application

	modified:   fec/static/scss/components/_table-styles.scss
	modified:   legal/templates/legal-search-results-murs.jinja
	modified:   legal/templates/partials/legal-search-results-mur.jinja
	modified:   legal/views.py
	
## Screenshots

![mur_sort](https://user-images.githubusercontent.com/5572856/217044232-080ae42c-eccf-4260-852e-99c048e39a0b.gif)

## Related PRs

Related PRs against other branches:

[#5246](https://github.com/fecgov/openFEC/pull/5246) Add sorting by case number and by advisory opinions number in legal/search

## How to test

- checkout feature/5261-sort-murs-by-case-no
- `npm run build`
- `npm run test-single`
- `pytest`
-  Go to http://127.0.0.1:8000/data/legal/search/murs/
- Test sort toggle on first column
- Apply some filters. Does it maintain the current sort order after applying filters?
- Test adding other filters

2023-02-06 18:22 UTC, patphongs commented
> If we want to repurpose it for these, I recommend we remove the JS from the MURs template and revise the script to work for all of them and put it under /`js/pages` or `/js/modules`

@johnnyporkchops You read my mind here. I'm pretty sure that the ADRs and AFs are developed in the same way as MURs. So it would be nice to repurpose the sort capability in those scenarios. Both use `case_no` as an identifier too. Can you try to put the script where we can easily grab it if we need it for those other legal docs?

2023-02-06 19:17 UTC, johnnyporkchops commented
> @ patphongs wrote: 
Can you try to put the script where we can easily grab it if we need it for those other legal docs

@patphongs, Good question. The script is inside the murs jinja template, so it would be easy to move to a separate script. Since the AF/ADR templates and views would also need to be edited, I was inclined to keep it in the murs template until then because those changes may inform how the JS gets revised to work for all the targeted legal docs. It could be its own file, or maybe  added to `legal.js` which is already included.

2023-02-06 22:07 UTC, pkfec commented
@johnnyporkchops deployed your changes to `Dev` space and observed the following issue with pagination

1. Sort by case_no ascending. Archived murs are shown, which is the expected behaviour. Click on next page. The next page results are showing current murs in descending order. **This is incorrect.** 

2. Sort by case_no descending. Current murs are shown, which is the expected behaviour. Click on next page. The next page results are showing currents murs in descending order. **This is correct.**

2023-02-06 23:48 UTC, johnnyporkchops commented
> @johnnyporkchops deployed your changes to `Dev` space and observed the following issue with pagination

@pkfec Good catch! This should be fixed now. Can you pull and redeploy to dev?

2023-02-07 18:03 UTC, pkfec commented
> data/legal/search/enforcement/

@johnnyporkchops [Redeployed](https://app.circleci.com/pipelines/github/fecgov/fec-cms/2440/workflows/57b01e62-280e-4367-a2d9-aa4967a9b882/jobs/5793) your latest changes to Dev space this afternoon. The sort works as expected. Great job fixing the pagination bug. I am now able to paginate the results in both asc and desc order.

Sorting by case_no works as expected!

2023-02-07 18:03 UTC, pkfec approved these changes

2023-02-07 22:09 UTC, JonellaCulmer approved these changes
Looks/works great from my perspective! Thanks @johnnyporkchops

2023-02-08 15:31 UTC, patphongs commented
> Since the AF/ADR templates and views would also need to be edited, I was inclined to keep it in the murs template until then because those changes may inform how the JS gets revised to work for all the targeted legal docs (especially if we include AOs which use `ao_no`)

Thanks for the additional clarification @johnnyporkchops. Keeping it in just the MUR template for now makes sense to me then.

2023-02-08 15:34 UTC, patphongs requested changes

2023-02-08 15:34 UTC, patphongs commented on tasks.py
> +    ('dev', lambda _, branch: branch == 'feature/5261-sort-murs-by-case-no'),
@johnnyporkchops Everything looks good, last change is can you please put this back to `develop`? After this change, I can merge.

2023-02-08 16:59 UTC, patphongs approved these changes
👍

2023-02-08 17:00 UTC, merged