Office page template
fecgov/fec-cms pull request #5636
Opened 2023-03-03 02:15 UTC by johnnyporkchops

## Summary (required)
Office page template. [Mural board of mockups](https://app.mural.co/t/fec4461/m/fec4461/1675268367751/9ddad9551d00a89a468b900e565729c5f1d13b95?sender=0bb5f432-316e-4530-91a5-0470dd7a1e46) for pages that will need to be built with this template
- Resolves #5602

(Include a summary of proposed changes and connect issue below)

### Required reviewers

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)

## Impacted areas of the application

General components of the application that this PR will affect:

-  

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- 

## System architecture updates (if applicable)

(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a description of those changes here and create a new ticket to update the system diagram)

2023-03-10 15:53 UTC, JonellaCulmer commented
@johnnyporkchops Everything looks great in dev. Just noted two things:
1. When linking to other pages like we will in the mockup below, will we able to use anchor links to those specific sections? Each office needs to be/have it's own section ID, right?
![Screen Shot 2023-03-10 at 10 49 49 AM](https://user-images.githubusercontent.com/31663028/224361650-274c7566-aad0-40a5-9d5a-54dca7595adc.png)

2. For footnotes, there isn't a clear place to enter a footnote at the bottom of the page, so I'm just using the extra information section at the bottom of the office section. Easy enough to do it that way but I was wondering if that was your intention?

2023-03-10 17:13 UTC, johnnyporkchops commented
> 1. When linking to other pages like we will in the mockup below, will we able to use anchor links to those specific sections? Each office needs to be/have it's own section ID, right?

@JonellaCulmer. Correct.  I'll  add a class or id to the H2 (or above the H2) that matches he office title replacing spaces with underscores or dashes. So it would be something like `id='office_of_the_commission_secretary'`. Then you could anchor link to is with an external link in the text editor.

> 2. For footnotes, there isn't a clear place to enter a footnote at the bottom of the page, so I'm just using the extra information section at the bottom of the office section. Easy enough to do it that way but I was wondering if that was your intention?

Yes,  thats the idea. Since it works that way, we don't need to create another field specifically for that

2023-03-13 21:11 UTC, johnnyporkchops commented
@JonellaCulmer foe anchoring to an office section, I will add  a separate  anchor item  above the H2-title for the office section instead of on the H2 to handle cases where we leave the H2-title off. 
(There is also the anchor option in Rich Text fields which might come in handy in certain situations, although it has limited capability )

2023-03-16 19:39 UTC, patphongs requested changes
Changes look great and works as expected @johnnyporkchops, just a small edit to put the develop branch back for the deploy hook. Then I will fully approve.

2023-03-16 19:39 UTC, patphongs commented on tasks.py
> +    ('dev', lambda _, branch: branch == 'feature/5602-office-page-template'),
Please update back to develop branch

2023-03-20 15:22 UTC, JonellaCulmer approved these changes
Everything looks great! Thanks, @johnnyporkchops

2023-03-20 16:35 UTC, patphongs approved these changes
👍 Thanks @johnnyporkchops !

2023-03-20 16:35 UTC, merged