4413 - Debts datatable
fecgov/fec-cms pull request #5765
Opened 2023-06-09 19:33 UTC by rfultz

## Summary

- Resolves #issue_number

Adding the debts datatable and links, behind a feature flag.

### Required reviewers

- UX
- Front-end
- Back-end?
- SME (not on localhost)
- Content? (not on localhost)

## Impacted areas of the application

- /data/
- /data/debts/

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- 

## System architecture updates (if applicable)

(If this pull request changes our [current system diagram](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram), include a description of those changes here and create a new ticket to update the system diagram)

2023-06-12 14:38 UTC, cnlucas commented
Will debts be added under loans here or maybe the loans section can be loans and debts?

![Screen Shot 2023-06-12 at 10 38 07 AM](https://github.com/fecgov/fec-cms/assets/66386084/e7618000-8b50-4a4e-9c74-91bc47b788e6)

2023-06-12 15:34 UTC, JonellaCulmer commented
@rfultz Here's the intro text for the debts datatable on the browse data page. 

Search debts owed by committees. Search by committee, creditor/debtor's name, coverage date, beginning balance and ending balance.

cc: @dorothyyeager

2023-06-12 17:41 UTC, rfultz commented on fec/data/templates/macros/tables.jinja
> +{%- macro summary(data, committee_id, cycle, office_or_committee, aggregate_cycles) -%}
All these new dashes are telling Jinja to delete the whitespace on that side of the code

2023-07-10 14:57 UTC, johnnyporkchops requested changes

2023-07-17 18:52 UTC, rfultz commented on fec/data/urls.py
>  if settings.FEATURES.get('debts'):
As far as I know. @JonellaCulmer ?

2023-07-21 17:42 UTC, rfultz commented on fec/data/urls.py
>  if settings.FEATURES.get('debts'):
To be clear, present / true shows the feature, which absent / negative switches it off

2023-08-01 14:43 UTC, cnlucas approved these changes
Works great, thank you

2023-09-27 17:38 UTC, JonellaCulmer approved these changes
This looked good from my perspective, thanks @rfultz

2023-09-27 18:42 UTC, merged