Expand keyword search on /updates to include html content
fecgov/fec-cms pull request #6214
Opened 2024-04-18 15:27 UTC by johnnyporkchops

## Summary (required)

- Resolves #6118
- Added search_updates function to convert html fields to a string and do a string search on them
- Preserve existing backend Postgres database search for pages with searchable fields types (non-html)
- Exclude duplicate search results  on rare occurrences where both search options return results for the same because  a page has both html and other database-searchable fields

### Required reviewers
one frontend AND one UX or content

## Impacted areas of the application
The `/updates` keyword search
modified:   home/views.py

## Screenshots

Coming soon...

## How to test

- checkout and run branch
- do a keyword search for a term that appears in an html block of a Digest, PressRelease, Record, or TipsForTreasurers page
- See example from issue:
    -  https://www.fec.gov/updates/?update_type=weekly-digest&search=MUR+6535

2024-04-18 15:39 UTC, JonellaCulmer commented
@kathycarothers Let me know if you'd like to pair on the testing for this.

2024-04-22 16:52 UTC, kathycarothers commented
@JonellaCulmer  yes let's pair for the testing

2024-04-23 18:10 UTC, JonellaCulmer approved these changes
Checked for the original issue MUR/digest that was not appearing and it is currently appearing as expected. Checked other areas and search appears to still be working when filtering by other publication type categories. Thanks, @johnnyporkchops

2024-04-23 18:11 UTC, kathycarothers approved these changes
Tested and worked. Thanks @johnnyporkchops

2024-04-23 18:55 UTC, patphongs requested changes
After this change, I can merge, thanks for your work on this, looks good!

2024-04-23 19:15 UTC, patphongs approved these changes
👍

2024-04-23 19:15 UTC, merged