Feature/6179 6180 national party account
fecgov/fec-cms pull request #6273
Opened 2024-05-17 19:10 UTC by rfultz

## Summary

- Resolves #6179 
- Resolves #6180 

Building the front-end for the national party accounts' receipts and disbursements datatables

### Required reviewers

- UX
- front-end for code
- back-end and/or SMEs for data accuracy

## Impacted areas of the application

- A couple new feature flags
- A couple new URLs
- A new link from [/data/browse-data/?tab=raising](http://127.0.0.1:8000/data/browse-data/?tab=raising)
- A new link from [/data/browse-data/?tab=spending](http://127.0.0.1:8000/data/browse-data/?tab=spending)
- A couple new datatables
- I snuck in fixes for a few typos and cleaned up some page source

## Screenshots

| Receipts  | Disbursements |
| ------------- | ------------- |
| Tab:![image](https://github.com/fecgov/fec-cms/assets/26720877/ae93752f-2619-4a97-a417-ca4a8d5219b9)  | Tab:![image](https://github.com/fecgov/fec-cms/assets/26720877/db098631-f98c-4cc3-b7e6-b8bc84d6ab8a)  |
| datatable:![image](https://github.com/fecgov/fec-cms/assets/26720877/69b0c1f1-0eb7-40b8-b2f1-b3553248a336) | datatable:![image](https://github.com/fecgov/fec-cms/assets/26720877/7816b219-a73d-4f58-86cf-0d9a8a4e6883)  |

## Related PRs

Related PRs against other branches:

None for CMS

## Known issues

**UX and SMEs**: when the right-side details panel is open, it scoots down lower than the table. Should we lose a table column?

## How to test

- pull the branch
- `npm i`
- `npm run build`
- `./manage.py runserver`

Default, with feature flags on for localhost:

- [/data/browse-data/?tab=raising](http://127.0.0.1:8000/data/browse-data/?tab=raising) should offer an option for 'National party account receipts'
- [/data/browse-data/?tab=spending](http://127.0.0.1:8000/data/browse-data/?tab=spending) should offer an option for 'National party account disbursements'
- Both of those pages should link to their respective tables
- Check all filters
- Spot check a wide variety of lines' ➲ details panel

To test feature flag:
- For receipts
   1. base.py, line 113, comment out `FEATURES['nat_party_acct_receipts'] = True`, **save**
   1. [/data/browse-data/?tab=raising](http://127.0.0.1:8000/data/browse-data/?tab=raising) should no longer mention 'National party account receipts'
   1. The [national party account receipts datatable page](http://127.0.0.1:8000/data/national-party-account-receipts/) should throw a 404
   1. restore the code in base.py, save
- For disbursements
   1. base.py, line 114, comment out `FEATURES['nat_party_acct_disbursements'] = True`, **save**
   1. [/data/browse-data/?tab=raising](http://127.0.0.1:8000/data/browse-data/?tab=spending) should no longer mention 'National party account disbursements'
   1. The [national party account disbursements datatable page](http://127.0.0.1:8000/data/national-party-account-disbursements/) should throw a 404
   1. restore the code in base.py, save

2024-05-28 16:47 UTC, patphongs requested changes
A couple of fixes for you @rfultz. There's some data issues in the API with line number data, but that's something that @bmathesonFEC is looking at. Let's target these changes for the release branch instead, so we're not pressured to have this in before the cut today.

2024-05-28 16:47 UTC, patphongs commented on fec/data/templates/partials/national-party-account-receipts-filter.jinja
> +    <p>TODO: No line number?</p>
No line number here, let's take out the TODO

2024-05-28 16:47 UTC, patphongs commented on fec/fec/static/js/templates/national-party-account-disbursements.hbs
> +    {{#panelRow "TODO: Filing date IS THIS A THING?"}}
Filing date is not a thing, let's remove

2024-05-28 16:47 UTC, patphongs commented on fec/fec/static/js/templates/national-party-account-disbursements.hbs
> +    {{#panelRow "TODO: Designation"}}
Leave this as "Designation" for now and we'll add a separate ticket to make a `spender_committee_designation_full`. This will change at a later date.

2024-05-28 16:47 UTC, patphongs commented on fec/data/constants.py
> +        {'k': 'F3X-29', 'label': 'Form 3X, line 29'},
There should also be line_number `F3X-21b`. @bmathesonFEC needs to double check whether we have this data in our API, as it returns no results when we filter by it. If it's not there, it's urgent it gets added. TBD.

2024-05-28 16:47 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +  {{ text.field('recipient_name', 'Recipient name or ID') }}
This needs to be a `typeahead.field` so that they can select a committee if it's there. Or just search by the name without selecting from the list.

2024-05-28 16:47 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +  {{ years.cycles('two_year_transaction_period', 'Report time period', show_tooltip=True)  }}
National party account data is only relevant up to 2014. Let's remove cap it as far back as 2014.

2024-05-28 16:47 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +    {{ text.field('image_number', 'CANT: Image number') }}
Remove "CANT" from label

2024-05-28 17:18 UTC, patphongs commented
@rfultz One more thing we noticed is that not all the filters (especially the newer ones added here) are not hooked up to the search tags or passed through as URL query parameters. Could you please add this capability so we can remain consistent?

2024-05-29 12:33 UTC, rfultz commented on fec/data/templates/layouts/main.jinja
> +  {%- set title = self.title() -%}
Yes, just polishing the way the HTML looks during view source. {%- and -%} tell the templates to close the whitespace before/after

2024-05-29 12:36 UTC, rfultz commented on fec/data/templates/partials/meta-tags.jinja
> +  ================================================== -#}
Cleaning up the way the source code looks in browsers, I didn't see any reason for these comments to be delivered to browsers

2024-05-29 13:42 UTC, rfultz commented on fec/data/constants.py
> +        {'k': 'F3X-29', 'label': 'Form 3X, line 29'},
Cool. 29 was the only value I saw; I figured others would chime in

2024-05-29 13:45 UTC, rfultz commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +  {{ years.cycles('two_year_transaction_period', 'Report time period', show_tooltip=True)  }}
So… set end_year to 2014?

2024-05-29 13:48 UTC, rfultz commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +    {{ text.field('image_number', 'CANT: Image number') }}
Should we keep the image number filter? `image_number` isn't a filterable field in the API (at least on stage)

2024-05-29 14:06 UTC, rfultz commented on fec/fec/static/js/pages/datatable-national-party-account-disbursements.js
> +    order: [[4, 'desc']],
It's JavaScript so 0-indexed. 4 = fifth = Date (I changed to 3 and the API gets angry)

2024-05-29 15:00 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +    {{ text.field('image_number', 'CANT: Image number') }}
@rfultz You're correct, `image_number` is only filterable in national party account receipts and not disbursements at this time. We'll make a new ticket to make it filterable.

2024-05-29 15:22 UTC, patphongs commented on fec/data/constants.py
> +        {'k': 'F3X-29', 'label': 'Form 3X, line 29'},
@rfultz We decided to remove the disbursements_line_numbers as a filter since there could be outliers outside of 29 and 21b.

2024-05-29 15:24 UTC, rfultz commented
> @rfultz We're missing committee clickthroughs to committee profile pages. Clicking on a committee name in the table should take you to their profile page.
> 
> cc: @patphongs



> @rfultz One more thing we noticed is that not all the filters (especially the newer ones added here) are not hooked up to the search tags or passed through as URL query parameters. Could you please add this capability so we can remain consistent?

Will be part of the next commit/push

2024-05-31 14:09 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +  {{ years.cycles('two_year_transaction_period', 'Report time period', show_tooltip=True)  }}
No problem, this can be a problem for another time

2024-05-31 14:53 UTC, patphongs requested changes
@rfultz Thanks for taking care of these fixes. I just have one small fix

2024-05-31 14:53 UTC, patphongs commented on fec/data/templates/partials/national-party-account-disbursements-filter.jinja
> +  {{ typeahead.field('recipient_name', 'Recipient name or ID') }}
We still need to be able to type and search by text as well as have the autosuggest pop up with committees to select. Can you add this additional param for this field? `allow_text=True`.

There's also a small issue I just discovered for the recipient_name in the API where that field should be able to take in a committee_id or just text string. Currently, it only accepts text because when I put in a recipient committee ID for that field, it returns 0 when it should be returning multiple. I've logged a [ticket](https://github.com/fecgov/openFEC/issues/5858) to fix that.

2024-05-31 15:14 UTC, patphongs approved these changes
Thanks for pushing up the last few changes @rfultz! This looks good to go 👍

2024-05-31 15:14 UTC, merged