6305 National Party Accounts Types Filters Labels
fecgov/fec-cms pull request #6359
Opened 2024-07-02 16:46 UTC by rfultz

## Summary

- Resolves #6305 

Updating the labels for the type filters for the National Party Accounts datatables

### Required reviewers

- UX?
- Front-end

## Impacted areas of the application

The national party accounts datatables' [receipts | disbursements] type filters

## Screenshots
Disbursements
<img width="466" alt="image" src="https://github.com/fecgov/fec-cms/assets/26720877/dc459f37-8ff9-4851-9565-7d8253608345">

Receipts
<img width="370" alt="image" src="https://github.com/fecgov/fec-cms/assets/26720877/4b8d352a-9d2e-4d1f-ac13-548d3c542aa6">

## Related PRs

None

## How to test

- pull the branch
- `./manage.py runserver`
- check [national party accounts disbursements](http://127.0.0.1:8000/data/national-party-account-disbursements/)' disbursement type filter (left column, Disbursement details)
- check [national party accounts receipts](http://127.0.0.1:8000/data/national-party-account-receipts/)' receipt type filter (left column, Receipt details)

2024-07-08 05:22 UTC, johnnyporkchops requested changes

2024-07-08 05:22 UTC, johnnyporkchops commented on fec/data/templates/macros/filters/dropdown-json.jinja
> +  <select id={{ name }} name="{{ name }}" data-filter-change="true" data-removeable-filter="true" class="dropdown">
It look like this is a mistake that got carried over every time we repurposed the original dropdown macro, shouldn't it be `select id="{{ name }}"` , with quotes? Every macro in this file has that.

2024-07-08 12:09 UTC, rfultz commented on fec/data/templates/macros/filters/dropdown-json.jinja
> +  <select id={{ name }} name="{{ name }}" data-filter-change="true" data-removeable-filter="true" class="dropdown">
Oh, nice catch! I've fixed a few of these in the latest push

2024-07-08 15:52 UTC, johnnyporkchops approved these changes
Looks good, thanks for making that one change!

2024-07-11 18:33 UTC, bmathesonFEC approved these changes
Just huddled with Jonella. Looks great, huge improvement on the codes/code wording. Thank you!

2024-07-11 18:35 UTC, JonellaCulmer commented
@rfultz My only concern is the low contrast between the header labeling and background.

2024-07-22 13:53 UTC, JonellaCulmer approved these changes
Approving under the assumption that the contrast issue will be resolved shortly.

2024-07-22 13:53 UTC, merged