6182, 6183 National Party Accounts Data on Single Pages
fecgov/fec-cms pull request #6406
Opened 2024-08-01 12:12 UTC by rfultz

## Summary

- Resolves #6182 
- Resolves #6183 

Adding the "National party headquarters, recounts and convention accounts" sections to single committee pages

### Required reviewers

- UX
- front-end
- data SME

## Impacted areas of the application

The single pages for committees

## Screenshots

<img width="312" alt="image" src="https://github.com/user-attachments/assets/9a308cfd-e3f0-4f90-b073-f2addd343be3">

<img width="313" alt="image" src="https://github.com/user-attachments/assets/44258dcf-d442-404a-abfe-d22d24208b49">

<img width="874" alt="image" src="https://github.com/user-attachments/assets/a2ef8a1d-cb47-421f-83c4-95d94ac9ca35">

<img width="873" alt="image" src="https://github.com/user-attachments/assets/accdc2ed-6086-453e-b22b-41cac26c89a5">

## Related PRs

nah

## KNOWN ISSUES / QUESTIONS
- **SME**: Right now the National party sections will appear on every committee's page. What are the rules to show it? e.g. when `committee.designation == '[?]'`
- **UX**:
   - Should the new section have _both_ kinds of coverage dates flags? (the sentence and the tag-like version)
   - Should the new section have both the "See the financial…" sentence _and_ the Export button?
   - Having both sections has given us too many top/bottom borders

## How to test

- Pull the branch
- `npm i`
- `npm run build`
- `./manage.py runserver`
- Test the feature flag negative
   - Edit base.py
   - Comment out lines 115 and/or 116, (`nat_party_acct_rec_single`, `nat_party_acct_dis_single`) (put a `#` at the front)
   - Save
   - Load a national party's page
   - Line 115 should have removed "National party headquarters, recounts and convention accounts" from the Raising tab—from the left menu and from the page's data
   - Line 116 should have removed "National party headquarters, recounts and convention accounts" from the Spending tab—from the left menu and from the page's data
- Test the feature flags
   - Edit base.py
   - Restore lines 115 and/or 116, (`nat_party_acct_rec_single`, `nat_party_acct_dis_single`)
   - Save
   - Load a national party's page
   - Line 115 should have added "National party headquarters, recounts and convention accounts" to Raising
   - Line 116 should have added "National party headquarters, recounts and convention accounts" to Spending
- Find a committee who isn't a national party committee, make sure its Raising and Spending tabs don't mention "National party headquarters…" at all **_THIS ISN'T CURRENTLY WORKING–SEE THE KNOWN ISSUES_**
- Check a national party committee ([C00000935](http://127.0.0.1:8000/data/committee/C00000935/) is the example in the comps)
- For both raising and spending:
   - Left menu "National party headquarters…" option should appear and jump correctly
   - Data should be accurate
   - New datatable should be functional (sorting, paging)
   - "Filter this data" button should link correctly
   - "Export" button should work correctly
   - Other sections' tables should work correctly (there was an issue early on where the "Disbursements" tables were fragmenting)

2024-08-02 14:20 UTC, PaulClark2 commented
@rfultz can we limit NPA by committee ID? Only national party committees should have this type of activity. The list is fairly short, and only seven committees have reported NPA activity, the six Democratic and Republican party committees and the Libertarian National Committee. 

|	cmte_id	|	cmte_nm	|
|	----	|	----	|
|	C00010603	|	DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE	|
|	C00042366	|	DSCC	|
|	C00000935	|	DCCC	|
|	C00003418	|	REPUBLICAN NATIONAL COMMITTEE	|
|	C00027466	|	NRSC	|
|	C00075820	|	NRCC	|
|	C00255695	|	LIBERTARIAN NATIONAL COMMITTEE, INC.	|
|	C00418103	|	LIBERTARIAN NATIONAL CONGRESSIONAL COMMITTEE INC	|
|	C00370221	|	GREEN PARTY OF THE UNITED STATES	|
|	C00428664	|	GREEN SENATORIAL CAMPAIGN COMMITTEE	|
|	C00279802	|	CONSTITUTION PARTY NATIONAL COMMITTEE	|
|	C00266759	|	NATURAL LAW PARTY OF THE UNITED STATES	|
|	C00331314	|	REFORM PARTY NATIONAL COMMITTEE	|
|	C00111476	|	SOCIALIST WORKERS NATIONAL CAMPAIGN COMMITTEE	|
|	C00129668	|	SOCIALIST NATIONAL COMMITTEE	|

2024-08-04 09:36 UTC, rfultz commented
@PaulClark2 is there a reliable way to test for whether it's an NPA? Like designation, type, etc? I could add the one-off list but changes would then require CMS updates rather than just DB edits

2024-08-05 14:59 UTC, patphongs requested changes
A few updates we discussed

2024-08-05 14:59 UTC, patphongs commented on fec/data/templates/partials/committee/spending.jinja
> +            <th scope="col">Receipt date</th>
Should be `Disbursement date`

2024-08-05 14:59 UTC, patphongs commented on fec/data/templates/partials/committee/raising.jinja
> +    {% if FEATURES.nat_party_acct_rec_single %}
Add a hardcoded list of NPA committees

2024-08-05 14:59 UTC, patphongs commented on fec/data/templates/partials/committee/raising.jinja
> +              <span class="t-big-data">{{ totals.receipts|currency }}</span>
Update to using `/national_party/totals/` endpoint passing `committee_id` and `two_year_transaction_period` as query parameters. Use `total_receipts`.

2024-08-05 14:59 UTC, patphongs commented on fec/data/templates/partials/committee/spending.jinja
> +              <span class="t-big-data">{{ totals.disbursements|currency }}</span>
Update to using `/national_party/totals/` endpoint passing `committee_id` and `two_year_transaction_period` as query parameters. Use `total_disbursements`.

2024-08-05 18:28 UTC, patphongs commented
@rfultz Things are looking good, just need to fix the pytest to account for the new `totals_national_party` addition.

```
=== short test summary info ===
FAILED fec/data/tests/test_committee.py::TestCommittee::test_base_case - ValueError: not enough values to unpack (expected 3, got 2)
FAILED fec/data/tests/test_committee.py::TestCommittee::test_fallback_cycle - ValueError: not enough values to unpack (expected 3, got 2)
FAILED fec/data/tests/test_committee.py::TestCommittee::test_host_f3x_summary_returns_standard_values - ValueError: not enough values to unpack (expected 3, got 2)
FAILED fec/data/tests/test_committee.py::TestCommittee::test_host_f4_summary - ValueError: not enough values to unpack (expected 3, got 2)
FAILED fec/data/tests/test_committee.py::TestCommittee::test_ie_summary - ValueError: not enough values to unpack (expected 3, got 2)
FAILED fec/data/tests/test_committee.py::TestCommittee::test_inaugural_summary - ValueError: not enough values to unpack (expected 3, got 2)
=== 6 failed, 96 passed, 290 warnings in 30.01s ===
```

2024-08-06 12:57 UTC, patphongs approved these changes
Thanks @rfultz, changes look good and thanks for following up with the tech debt [issue](https://github.com/fecgov/fec-cms/issues/6409). Noting that the `None` for the NPA totals will be fixed once the openFEC [PR](https://github.com/fecgov/openFEC/pull/5929) is merged.

2024-08-06 15:58 UTC, JonellaCulmer approved these changes
Everything looks good to me. Will check to make sure everything looks good still after Priya is finished her API work. Approving under the assumption that "None" will be fixed with that work. Thanks for your work on this part @rfultz

2024-08-06 15:58 UTC, merged