Sass Deprecation Warnings
fecgov/fec-cms pull request #6422
Opened 2024-08-08 18:26 UTC by rfultz

## Summary

- Resolves #6387 

Addressing Sass deprecation and, while adjusting everything, added some Sass formatting

### Required reviewers

- front-end
- anyone who'd like to scour for visual changes

## Impacted areas of the application

The entire front-end, _but_ most changes hit mixins and seemed to mostly fall on
- column widths and offsets (like 2 columns, -1)
- icons, especially on buttons
- this is _not_ a complete list—there were nearly 200 files changed

## Screenshots

Should be zero visual changes

No longer getting screen after screen of deprecation warnings!

![image](https://github.com/user-attachments/assets/c89a9fbd-918d-4808-988a-60ab20a13f03)

## Related PRs

None

## How to test

- Pull the branch
- `npm i`
- `npm run build`
- `./manage.py runserver`
- Check _every_ part of every type of page across every width. There should be zero visual differences.
- Pages/templates I've reviewed across widths, which I'd like to have others try to break
  - [Homepage](http://127.0.0.1:8000/)
  - [About - FEC](http://127.0.0.1:8000/about/)
  - [About - Leadership](http://127.0.0.1:8000/about/leadership-and-structure/)
  - [About - Org chart](http://127.0.0.1:8000/about/leadership-and-structure/fec-offices/) (Names and titles could be outdated but style should be right)
  - [Contact analyst](http://127.0.0.1:8000/help-candidates-and-committees/question-rad/)
  - [Contact](http://127.0.0.1:8000/contact/)
  - [Data landing](http://127.0.0.1:8000/data/)
  - [Data - browse](http://127.0.0.1:8000/data/browse-data/)
  - [Data - election search](http://127.0.0.1:8000/data/elections/)
  - [Data - elections - House](http://127.0.0.1:8000/data/elections/house/)
  - [Data - elections - President](http://127.0.0.1:8000/data/elections/president/)
  - [Data - presidential map](http://127.0.0.1:8000/data/candidates/president/presidential-map/)
  - [Data - raising by the numbers](http://127.0.0.1:8000/data/raising-bythenumbers/)
  - [Data - receipts / datatables](http://127.0.0.1:8000/data/receipts/)
  - [H4CC](http://127.0.0.1:8000/help-candidates-and-committees/)
  - [Legal - admin fines calculator](http://127.0.0.1:8000/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine)
  - [OIG](http://127.0.0.1:8000/office-inspector-general/)
  - [Search](http://127.0.0.1:8000/search/)
- Other unique types—or areas—of pages
  - Others I've forgotten
  - Others?
  - More?

2025-01-21 18:48 UTC, johnnyporkchops requested changes

2025-01-21 18:48 UTC, johnnyporkchops commented on fec/fec/static/scss/components/_table-styles.scss
> +    (device-width >= 650px) and (device-width <= 1024px) {
@rfultz I am not sure if this iis where the issue is, but the responsive mobile styles for these tables no longer works on this branch

2025-01-21 20:19 UTC, johnnyporkchops commented on fec/fec/static/scss/_global.scss
> +body:before {
@rfultz Dont forget this

2025-01-21 20:24 UTC, johnnyporkchops approved these changes
Looks good, thanks for fixing the mobile table issue. Please remove the green label and I can merge

2025-01-22 13:21 UTC, rfultz commented on fec/fec/static/scss/components/_table-styles.scss
> +    (device-width >= 650px) and (device-width <= 1024px) {
Nice catch!

For the record, `width <=` doesn't seem to work but the older `max-width:` does

2025-01-22 14:33 UTC, merged