Move state and territory filter
fecgov/fec-cms pull request #6490
Opened 2024-09-25 21:45 UTC by patphongs

## Summary (required)

- Resolves #6196 

Per [ticket](https://github.com/fecgov/fec-cms/issues/6196) specifications, re-arrange filters and update text accordingly.

### Required reviewers

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)

## Impacted areas of the application

General components of the application that this PR will affect:

-  Individual contributions datatable filters
- Receipt datatable filters

## Screenshots

### Receipts datatable
<img width="293" alt="Screenshot 2024-09-25 at 5 15 24 PM" src="https://github.com/user-attachments/assets/71f3536c-0018-45c0-8aa1-b7e13f5e3098">
<img width="298" alt="Screenshot 2024-09-25 at 5 15 03 PM" src="https://github.com/user-attachments/assets/06860b81-7991-46eb-b1f2-7c193f7ac063">
<img width="294" alt="Screenshot 2024-09-25 at 5 14 33 PM" src="https://github.com/user-attachments/assets/5a5b7abf-a00c-4cfc-8638-41df689c9bb5">
<img width="287" alt="Screenshot 2024-09-25 at 5 14 06 PM" src="https://github.com/user-attachments/assets/46c3a02f-49ee-4aaf-8d09-8d093d45ca13">

### Individual contributions datatable
<img width="297" alt="Screenshot 2024-09-25 at 5 24 10 PM" src="https://github.com/user-attachments/assets/efd80496-efe4-48d0-8f58-bae0ea7e2033">
<img width="295" alt="Screenshot 2024-09-25 at 5 23 55 PM" src="https://github.com/user-attachments/assets/72052132-4417-4fb9-af42-dfe49568b239">
<img width="291" alt="Screenshot 2024-09-25 at 5 23 32 PM" src="https://github.com/user-attachments/assets/a34176b6-2b19-494d-9b32-dd85cf317646">
<img width="295" alt="Screenshot 2024-09-25 at 5 41 49 PM" src="https://github.com/user-attachments/assets/de88cc4d-bdaa-4861-a1e2-5ca30bb115d0">

## How to test

- Checkout this branch
- `npm run build-production`
- `./manage.py runserver`
- Check the Individual contributions datatable filters: http://localhost:8000/data/receipts/individual-contributions/
- Check the Receipts datatable filters: http://localhost:8000/data/receipts/

2024-10-01 21:29 UTC, JonellaCulmer commented
@patphongs, I'm hoping we can handle each of the updated sections the same way. Here are (mostly) screenshots of the Time period accordion but the changes affect multiple sections. I'd like to change the margin-top (5) and padding-top (10) in two areas, as well as the line height in the paragraphs (1.5). This removes some of the extra space above the new paragraphs and tightens up the text a bit. There's also a type: `accross`. Please let me know if I should present this all differently to you. 

### Accordion padding top (10)
![Screenshot 2024-10-01 at 5 24 52 PM](https://github.com/user-attachments/assets/77278a31-b23a-4309-9666-4d4f1cb71cfb)

### Label margin top (5)
![Screenshot 2024-10-01 at 5 12 43 PM](https://github.com/user-attachments/assets/20031cdc-0711-4a00-828d-f25149deb1e2)

### Small typo
![Screenshot 2024-10-01 at 5 13 01 PM](https://github.com/user-attachments/assets/45bdc802-0b5d-41d2-9862-74dbce02af30)

### Line height (1.5)
![Screenshot 2024-10-01 at 5 13 31 PM](https://github.com/user-attachments/assets/f70efc7f-ab22-46db-9ba8-418f10f971e5)
![Screenshot 2024-10-01 at 5 27 43 PM](https://github.com/user-attachments/assets/14cb3269-c7be-4fc3-88e3-e05955378bc7)
![Screenshot 2024-10-01 at 5 27 33 PM](https://github.com/user-attachments/assets/188bb07b-67d9-4be5-89a0-87ecce54e8d7)

2025-01-07 13:54 UTC, rfultz requested changes

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/individual-contributions-filter.jinja
> +    <label class="label--help u-margin--top">When searching by contribution details and across multiple time periods, choose one or more fields: <br /> ecipient name or ID, contributor name or ID, ci
'ecipient'? 😄

The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/receipts-filter.jinja
> +  {{ states.field('contributor_state', minor_label_text = True, helper_text = 'When searching by state or territory, and across multiple time periods, choose one or more fields: recipient name or ID,
The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/receipts-filter.jinja
> +    <label class="label--help u-margin--top">When searching accross multiple time periods, choose one or more fields: <br /> recipient name or ID, source name or ID, city, ZIP code, occupation, emplo
Can we remove a c from 'accross'?

The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/receipts-filter.jinja
> +    <label class="label--help u-margin--top">When searching by recipient committee type and across multiple time periods, choose one or more fields: <br /> recipient name or ID, source name or ID, ci
The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/receipts-filter.jinja
> +    <label class="label--help u-margin--top">When searching by receipt details and across multiple time periods, choose one or more fields: <br /> recipient name or ID, source name or ID, city, ZIP c
The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/individual-contributions-filter.jinja
> +    <label class="label--help u-margin--top">When searching by recipient committee type and across multiple time periods, choose one or more fields: <br /> recipient name or ID, contributor name or I
The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/individual-contributions-filter.jinja
> +  {{ states.field('contributor_state', minor_label_text = True, helper_text = 'When searching by state or territory, and across multiple time periods, choose one or more fields: recipient name or ID,
The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/data/templates/partials/individual-contributions-filter.jinja
> +    <label class="label--help u-margin--top">When searching accross multiple time periods, choose one or more fields: <br /> recipient name or ID, contributor name or ID, city, ZIP code, occupation o
Can we remove a c from 'accross'?

The issue ticket is inconsistent on 'occupation or employer, or' vs 'occupation or employer, or'

2025-01-07 13:54 UTC, rfultz commented on fec/fec/static/js/pages/datatable-individual-contributions.js
> +      '<p><p>You&#39;re trying to search across multiple time periods. Filter by recipient name or ID, other contributor details, or image number.</p>',
`<p><p>`

2026-08-03 13:55 UTC, closed without merging

2026-08-03 13:55 UTC, patphongs commented
I don't think we're ready for this yet. We need to test performance more. Closing for now and we can revisit at a later time.