4942 Datatable Details Panel to Child Rows
fecgov/fec-cms pull request #6528
Opened 2024-10-25 13:10 UTC by rfultz

## Summary

- Resolves #4942 

(Include a summary of proposed changes and connect issue below)

### Required reviewers

(Include who is required to review prior to merge. For example: One designer and two front end developer reviews are required prior to merge)

## Impacted areas of the application

General components of the application that this PR will affect:

-  

## Screenshots

(Include a screenshot of the new/updated features in context (“in the wild”). If it is an interface change, include both before and after screenshots)

## Related PRs

Related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

## How to test

(Include any information that may be helpful to the reviewer(s). This might include links to sample pages to test or any local environmental setup that is unusual such as environment variable (never credentials), API version to point to, etc)

- [ ] Spending
   - [ ] [Party-coordinated expenditures](http://127.0.0.1:8000/data/party-coordinated-expenditures/)
- [ ] Reports & filings
   - [ ] [Pac/Party](http://127.0.0.1:8000/data/reports/pac-party/)
   - [ ] Candidate [House/Senate](http://127.0.0.1:8000/data/reports/house-senate/) | [Presidential](http://127.0.0.1:8000/data/reports/presidential/)

2024-10-25 15:32 UTC, rfultz commented
@JonellaCulmer some things I wanted to run by you…

Should this table have a title? I don't like that it's top-aligned with a table that does have a title. IE-only reports has the same issue.
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/9cfff53a-ef2d-44e6-a6cb-091236e45ca7">

Is there enough visual connection between the original row and its details?
Is there enough difference between the open row + its details and the other rows?
![image](https://github.com/user-attachments/assets/11241140-0853-4f8d-8874-1cfeeb6f0144)

Should we visually separate multiple open rows?
![image](https://github.com/user-attachments/assets/34024053-5b48-4989-9f34-f4679c6085e5)

For the medium widths, the table heads were too wide and were colliding with the "Open image" button so I bumped them down. I don't like that table-wide gap to the left of "Open image". What about putting a line break in "Transaction information"? Something better?
![image](https://github.com/user-attachments/assets/b4cd4a54-4611-4230-9f07-a574c26b984d)

2024-11-18 22:26 UTC, johnnyporkchops requested changes
tested locally and works well. Left on comment about zebra striping. Also I agree that there might be a  confusing visual effect between the way parent row's cells line up with  panel's  columns

2025-02-27 17:20 UTC, rfultz commented on fec/fec/static/scss/components/_datatable-details-row.scss
> +.dt-details {
I've got a change headed up to fix that. Now we just need styles for the details area

2026-04-14 17:00 UTC, patphongs reviewed
@rfultz So far I've found one thing that needs to be revisited. I'll be looking for more soon.

2026-04-14 17:00 UTC, patphongs commented on fec/fec/static/scss/entity.scss
> -@import 'components/committee-snapshot';
I think removing and adding certain styles within this file has broken the individual candidate and committee datatables. Some styling work should account for these pages as well.

<img width="1494" height="889" alt="Image" src="https://github.com/user-attachments/assets/26d9efa9-a930-45ee-a06b-186425857226" />

2026-04-23 12:45 UTC, rfultz commented on fec/fec/static/scss/entity.scss
> -@import 'components/committee-snapshot';
<img width="905" height="662" alt="image" src="https://github.com/user-attachments/assets/aeb3b3a6-43ee-4643-beeb-a343ba907875" />
<img width="464" height="533" alt="image" src="https://github.com/user-attachments/assets/6b06e633-3dfa-4e4f-a529-3897711964fb" />

2026-04-23 13:26 UTC, rfultz commented
> tested locally and works well. Left on comment about zebra striping. Also I agree that there might be a confusing visual effect between the way parent row's cells line up with panel's columns

The zebra striping has been removed and the child rows' layout has been overhauled

2026-04-28 15:45 UTC, patphongs approved these changes
@rfultz The updates you made look good. The only thing that was still buggy was clicking quickly through the rows caused some rows to remain selected with low contrast black text. The issue was a stale async response. If you click row A, then row B before A’s details fetch finishes, A’s callback could still run later and reapply the open/selected styling. I added a [patch](https://github.com/fecgov/fec-cms/pull/6528/changes/a17be1581bba03468772ea961d5c4dc6b1168d78) so that only the most recent click is allowed to render details, and it clears aria-details whenever rows are closed. Please take a look and let me know what you think. If this all works for you, I'm good with merging it. 

**Bug before patch:**
<img width="1214" height="616" alt="Screenshot 2026-04-28 at 11 33 55 AM" src="https://github.com/user-attachments/assets/cacdea28-e970-463f-bc5c-aa9f841e365f" />

2026-04-28 17:00 UTC, merged