Error handling and logging for global and policy searches
fecgov/fec-cms pull request #6581
Opened 2024-12-04 22:18 UTC by johnnyporkchops

## Summary

- Resolves #6525

- Handle errors for the global site search and Policy Guidance search when the FEC API or search.gov API  do not return search-result data
- Use a catch-all  `Try/Except` block handle  `Connection Errors` when the FEC API  endpoints (Candidtes or Committees) or search.gov  API  are not responding. Also handle `Key Error`, `JSON Decode Error` or any other error that arises when the data retunred is not processable, search-result json.
- Render an error message to the search-result page and log errors in server logs.

### Required reviewers
One frontend, One UX

## Impacted areas of the application

General components of the application that this PR will affect:

 - Global site search 
 - Policy Guidance search

	modified:   fec/static/scss/components/_messages.scss
	modified:   search/templates/search/policy_guidance_search_page.html
	modified:   search/templates/search/search.html
	modified:   search/views.py

## How to test

-  Export the `SEARCHGOV_API_ACCESS_KEY` and `SEARCHGOV_POLICY_GUIDANCE_KEY` in terminal 
-  `npm  run build-sass`
- Use the global site search box or [Policy Guidance search  box](http://127.0.0.1:8000/legal-resources/policy-and-other-guidance/guidance-documents/)
- Test a `JSON Decode Error`:  Break the search.gov URL by changing a character in the URL in `serach/views.py` line 113.
- Test a `Key Error` by exporting the  wrong access key for search.gov, like `export SEARCHGOV_API_ACCESS_KEY=1234"
- Test  a `Connection Error`  by changing the url on line 113 of `serach/views.py` to a site that does nor exist like: https://www.doesnotexist.com
- See the error messages on the results page
- See the errors logged in your terminal
- You can use this  string to see  how errors are handled when there are no-results : `tkts`

2025-05-08 13:58 UTC, pkfec approved these changes
Looks good, thanks @johnnyporkchops

2025-05-09 14:37 UTC, johnnyporkchops commented
@JonellaCulmer Requested changes have been made. Please merge

2025-05-12 15:11 UTC, rfultz requested changes
Oof. Good work! It's always harder work to catch, replicate, and address all of the possible error states.

I add a few single-line requests but this may be a bit trickier:

When I break both 'candidates' and 'committees' (lines 17 & 30 in search/views.py), I get another section at the top and it doesn't have a header. Breaking only candidates or only committees doesn't show that untitled section.
<img width="673" alt="image" src="https://github.com/user-attachments/assets/b2e5f32c-9449-404e-bcae-ed7fa1352442" />

2025-05-12 15:17 UTC, JonellaCulmer commented on fec/search/views.py
> +            <p>This section failed to load. Check FEC.gov status page to see if we are experiencing a temporary outage.
That's a great catch, thank you, Robert.

2025-05-12 15:34 UTC, JonellaCulmer approved these changes
Approving under the assumption that the changes recommended by Robert will be incorporated prior to merge. Thanks for all your work on this! This will really help clarify things when stuff goes down.

2025-05-12 17:37 UTC, johnnyporkchops commented on fec/search/views.py
> +import logging
@rfultz We are just logging to the usual logs, so if we get an issue from a user that an endpoint is not responding, we can tail the logs for some context.

2025-05-12 17:39 UTC, johnnyporkchops commented on fec/search/views.py
> +        r = requests.get('https://api.gsa.gov/technology/searchgov/v2/results/i14yX', params=params)
thanks @rfultz! that as a testing break and it inadvertently committed.

2025-05-12 18:02 UTC, rfultz approved these changes
Woo hoo!

2025-05-12 18:03 UTC, merged